// <auto-generated/>
#if !PUREDI_API_SUPPRESSION || PUREDI_API_V1
#pragma warning disable
namespace Pure.DI
{    
    /// <summary>
    /// Represents the generic type arguments marker for a reference type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal abstract class TT { }

    /// <summary>
    /// Represents the generic type arguments marker for a value type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal struct TTS { }

    /// <summary>
    /// Represents the generic type arguments marker for a enum type.
    /// </summary>
    [GenericTypeArgument]
    internal enum TTE { }

#if !NET35 && !NET20

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IDisposable"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTDisposable: global::System.IDisposable { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IComparable"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparable: global::System.IComparable { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IComparable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparable<in T>: global::System.IComparable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IEquatable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEquatable<T>: global::System.IEquatable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEnumerable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEnumerable<out T>: global::System.Collections.Generic.IEnumerable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEnumerator}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEnumerator<out T>: global::System.Collections.Generic.IEnumerator<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.ICollection}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTCollection<T>: global::System.Collections.Generic.ICollection<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTList<T>: global::System.Collections.Generic.IList<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.ISet}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTSet<T>: global::System.Collections.Generic.ISet<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IComparer}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparer<in T>: global::System.Collections.Generic.IComparer<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEqualityComparer}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEqualityComparer<in T>: global::System.Collections.Generic.IEqualityComparer<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IDictionary}TKey, TValue}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTDictionary<TKey, TValue>: global::System.Collections.Generic.IDictionary<TKey, TValue> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IObservable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTObservable<out T>: global::System.IObservable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IObserver}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTObserver<in T>: global::System.IObserver<T> { }
    
#endif

#if NETSTANDARD || NET || NETCOREAPP || NET45_OR_GREATER

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IReadOnlyCollection}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTReadOnlyCollection<out T>: global::System.Collections.Generic.IReadOnlyCollection<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IReadOnlyList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTReadOnlyList<out T>: global::System.Collections.Generic.IReadOnlyList<T> { }
    
#endif

#if NET || NETCOREAPP

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableList<T>: global::System.Collections.Immutable.IImmutableList<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableSet}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableSet<T>: global::System.Collections.Immutable.IImmutableSet<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableQueue}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableQueue<T>: global::System.Collections.Immutable.IImmutableQueue<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableStack}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableStack<T>: global::System.Collections.Immutable.IImmutableStack<T> { }
    
#endif

    /// <summary>
    /// Represents the generic type arguments marker for a reference type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal abstract class TT1 { }

    /// <summary>
    /// Represents the generic type arguments marker for a value type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal struct TTS1 { }

    /// <summary>
    /// Represents the generic type arguments marker for a enum type.
    /// </summary>
    [GenericTypeArgument]
    internal enum TTE1 { }

#if !NET35 && !NET20

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IDisposable"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTDisposable1: global::System.IDisposable { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IComparable"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparable1: global::System.IComparable { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IComparable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparable1<in T>: global::System.IComparable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IEquatable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEquatable1<T>: global::System.IEquatable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEnumerable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEnumerable1<out T>: global::System.Collections.Generic.IEnumerable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEnumerator}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEnumerator1<out T>: global::System.Collections.Generic.IEnumerator<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.ICollection}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTCollection1<T>: global::System.Collections.Generic.ICollection<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTList1<T>: global::System.Collections.Generic.IList<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.ISet}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTSet1<T>: global::System.Collections.Generic.ISet<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IComparer}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparer1<in T>: global::System.Collections.Generic.IComparer<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEqualityComparer}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEqualityComparer1<in T>: global::System.Collections.Generic.IEqualityComparer<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IDictionary}TKey, TValue}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTDictionary1<TKey, TValue>: global::System.Collections.Generic.IDictionary<TKey, TValue> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IObservable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTObservable1<out T>: global::System.IObservable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IObserver}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTObserver1<in T>: global::System.IObserver<T> { }
    
#endif

#if NETSTANDARD || NET || NETCOREAPP || NET45_OR_GREATER

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IReadOnlyCollection}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTReadOnlyCollection1<out T>: global::System.Collections.Generic.IReadOnlyCollection<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IReadOnlyList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTReadOnlyList1<out T>: global::System.Collections.Generic.IReadOnlyList<T> { }
    
#endif

#if NET || NETCOREAPP

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableList1<T>: global::System.Collections.Immutable.IImmutableList<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableSet}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableSet1<T>: global::System.Collections.Immutable.IImmutableSet<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableQueue}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableQueue1<T>: global::System.Collections.Immutable.IImmutableQueue<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableStack}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableStack1<T>: global::System.Collections.Immutable.IImmutableStack<T> { }
    
#endif

    /// <summary>
    /// Represents the generic type arguments marker for a reference type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal abstract class TT2 { }

    /// <summary>
    /// Represents the generic type arguments marker for a value type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal struct TTS2 { }

    /// <summary>
    /// Represents the generic type arguments marker for a enum type.
    /// </summary>
    [GenericTypeArgument]
    internal enum TTE2 { }

#if !NET35 && !NET20

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IDisposable"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTDisposable2: global::System.IDisposable { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IComparable"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparable2: global::System.IComparable { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IComparable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparable2<in T>: global::System.IComparable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IEquatable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEquatable2<T>: global::System.IEquatable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEnumerable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEnumerable2<out T>: global::System.Collections.Generic.IEnumerable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEnumerator}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEnumerator2<out T>: global::System.Collections.Generic.IEnumerator<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.ICollection}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTCollection2<T>: global::System.Collections.Generic.ICollection<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTList2<T>: global::System.Collections.Generic.IList<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.ISet}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTSet2<T>: global::System.Collections.Generic.ISet<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IComparer}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparer2<in T>: global::System.Collections.Generic.IComparer<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEqualityComparer}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEqualityComparer2<in T>: global::System.Collections.Generic.IEqualityComparer<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IDictionary}TKey, TValue}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTDictionary2<TKey, TValue>: global::System.Collections.Generic.IDictionary<TKey, TValue> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IObservable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTObservable2<out T>: global::System.IObservable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IObserver}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTObserver2<in T>: global::System.IObserver<T> { }
    
#endif

#if NETSTANDARD || NET || NETCOREAPP || NET45_OR_GREATER

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IReadOnlyCollection}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTReadOnlyCollection2<out T>: global::System.Collections.Generic.IReadOnlyCollection<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IReadOnlyList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTReadOnlyList2<out T>: global::System.Collections.Generic.IReadOnlyList<T> { }
    
#endif

#if NET || NETCOREAPP

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableList2<T>: global::System.Collections.Immutable.IImmutableList<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableSet}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableSet2<T>: global::System.Collections.Immutable.IImmutableSet<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableQueue}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableQueue2<T>: global::System.Collections.Immutable.IImmutableQueue<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableStack}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableStack2<T>: global::System.Collections.Immutable.IImmutableStack<T> { }
    
#endif

    /// <summary>
    /// Represents the generic type arguments marker for a reference type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal abstract class TT3 { }

    /// <summary>
    /// Represents the generic type arguments marker for a value type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal struct TTS3 { }

    /// <summary>
    /// Represents the generic type arguments marker for a enum type.
    /// </summary>
    [GenericTypeArgument]
    internal enum TTE3 { }

#if !NET35 && !NET20

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IDisposable"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTDisposable3: global::System.IDisposable { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IComparable"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparable3: global::System.IComparable { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IComparable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparable3<in T>: global::System.IComparable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IEquatable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEquatable3<T>: global::System.IEquatable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEnumerable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEnumerable3<out T>: global::System.Collections.Generic.IEnumerable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEnumerator}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEnumerator3<out T>: global::System.Collections.Generic.IEnumerator<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.ICollection}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTCollection3<T>: global::System.Collections.Generic.ICollection<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTList3<T>: global::System.Collections.Generic.IList<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.ISet}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTSet3<T>: global::System.Collections.Generic.ISet<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IComparer}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparer3<in T>: global::System.Collections.Generic.IComparer<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEqualityComparer}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEqualityComparer3<in T>: global::System.Collections.Generic.IEqualityComparer<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IDictionary}TKey, TValue}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTDictionary3<TKey, TValue>: global::System.Collections.Generic.IDictionary<TKey, TValue> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IObservable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTObservable3<out T>: global::System.IObservable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IObserver}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTObserver3<in T>: global::System.IObserver<T> { }
    
#endif

#if NETSTANDARD || NET || NETCOREAPP || NET45_OR_GREATER

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IReadOnlyCollection}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTReadOnlyCollection3<out T>: global::System.Collections.Generic.IReadOnlyCollection<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IReadOnlyList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTReadOnlyList3<out T>: global::System.Collections.Generic.IReadOnlyList<T> { }
    
#endif

#if NET || NETCOREAPP

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableList3<T>: global::System.Collections.Immutable.IImmutableList<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableSet}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableSet3<T>: global::System.Collections.Immutable.IImmutableSet<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableQueue}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableQueue3<T>: global::System.Collections.Immutable.IImmutableQueue<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableStack}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableStack3<T>: global::System.Collections.Immutable.IImmutableStack<T> { }
    
#endif

    /// <summary>
    /// Represents the generic type arguments marker for a reference type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal abstract class TT4 { }

    /// <summary>
    /// Represents the generic type arguments marker for a value type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal struct TTS4 { }

    /// <summary>
    /// Represents the generic type arguments marker for a enum type.
    /// </summary>
    [GenericTypeArgument]
    internal enum TTE4 { }

#if !NET35 && !NET20

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IDisposable"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTDisposable4: global::System.IDisposable { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IComparable"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparable4: global::System.IComparable { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IComparable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparable4<in T>: global::System.IComparable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IEquatable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEquatable4<T>: global::System.IEquatable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEnumerable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEnumerable4<out T>: global::System.Collections.Generic.IEnumerable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEnumerator}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEnumerator4<out T>: global::System.Collections.Generic.IEnumerator<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.ICollection}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTCollection4<T>: global::System.Collections.Generic.ICollection<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTList4<T>: global::System.Collections.Generic.IList<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.ISet}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTSet4<T>: global::System.Collections.Generic.ISet<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IComparer}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparer4<in T>: global::System.Collections.Generic.IComparer<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEqualityComparer}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEqualityComparer4<in T>: global::System.Collections.Generic.IEqualityComparer<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IDictionary}TKey, TValue}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTDictionary4<TKey, TValue>: global::System.Collections.Generic.IDictionary<TKey, TValue> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IObservable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTObservable4<out T>: global::System.IObservable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IObserver}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTObserver4<in T>: global::System.IObserver<T> { }
    
#endif

#if NETSTANDARD || NET || NETCOREAPP || NET45_OR_GREATER

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IReadOnlyCollection}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTReadOnlyCollection4<out T>: global::System.Collections.Generic.IReadOnlyCollection<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IReadOnlyList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTReadOnlyList4<out T>: global::System.Collections.Generic.IReadOnlyList<T> { }
    
#endif

#if NET || NETCOREAPP

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableList4<T>: global::System.Collections.Immutable.IImmutableList<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableSet}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableSet4<T>: global::System.Collections.Immutable.IImmutableSet<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableQueue}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableQueue4<T>: global::System.Collections.Immutable.IImmutableQueue<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableStack}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableStack4<T>: global::System.Collections.Immutable.IImmutableStack<T> { }
    
#endif

    /// <summary>
    /// Represents the generic type arguments marker for a reference type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal abstract class TT5 { }

    /// <summary>
    /// Represents the generic type arguments marker for a value type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal struct TTS5 { }

    /// <summary>
    /// Represents the generic type arguments marker for a enum type.
    /// </summary>
    [GenericTypeArgument]
    internal enum TTE5 { }

#if !NET35 && !NET20

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IDisposable"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTDisposable5: global::System.IDisposable { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IComparable"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparable5: global::System.IComparable { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IComparable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparable5<in T>: global::System.IComparable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IEquatable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEquatable5<T>: global::System.IEquatable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEnumerable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEnumerable5<out T>: global::System.Collections.Generic.IEnumerable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEnumerator}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEnumerator5<out T>: global::System.Collections.Generic.IEnumerator<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.ICollection}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTCollection5<T>: global::System.Collections.Generic.ICollection<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTList5<T>: global::System.Collections.Generic.IList<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.ISet}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTSet5<T>: global::System.Collections.Generic.ISet<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IComparer}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparer5<in T>: global::System.Collections.Generic.IComparer<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEqualityComparer}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEqualityComparer5<in T>: global::System.Collections.Generic.IEqualityComparer<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IDictionary}TKey, TValue}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTDictionary5<TKey, TValue>: global::System.Collections.Generic.IDictionary<TKey, TValue> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IObservable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTObservable5<out T>: global::System.IObservable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IObserver}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTObserver5<in T>: global::System.IObserver<T> { }
    
#endif

#if NETSTANDARD || NET || NETCOREAPP || NET45_OR_GREATER

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IReadOnlyCollection}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTReadOnlyCollection5<out T>: global::System.Collections.Generic.IReadOnlyCollection<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IReadOnlyList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTReadOnlyList5<out T>: global::System.Collections.Generic.IReadOnlyList<T> { }
    
#endif

#if NET || NETCOREAPP

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableList5<T>: global::System.Collections.Immutable.IImmutableList<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableSet}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableSet5<T>: global::System.Collections.Immutable.IImmutableSet<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableQueue}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableQueue5<T>: global::System.Collections.Immutable.IImmutableQueue<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableStack}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableStack5<T>: global::System.Collections.Immutable.IImmutableStack<T> { }
    
#endif

    /// <summary>
    /// Represents the generic type arguments marker for a reference type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal abstract class TT6 { }

    /// <summary>
    /// Represents the generic type arguments marker for a value type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal struct TTS6 { }

    /// <summary>
    /// Represents the generic type arguments marker for a enum type.
    /// </summary>
    [GenericTypeArgument]
    internal enum TTE6 { }

#if !NET35 && !NET20

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IDisposable"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTDisposable6: global::System.IDisposable { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IComparable"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparable6: global::System.IComparable { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IComparable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparable6<in T>: global::System.IComparable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IEquatable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEquatable6<T>: global::System.IEquatable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEnumerable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEnumerable6<out T>: global::System.Collections.Generic.IEnumerable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEnumerator}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEnumerator6<out T>: global::System.Collections.Generic.IEnumerator<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.ICollection}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTCollection6<T>: global::System.Collections.Generic.ICollection<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTList6<T>: global::System.Collections.Generic.IList<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.ISet}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTSet6<T>: global::System.Collections.Generic.ISet<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IComparer}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparer6<in T>: global::System.Collections.Generic.IComparer<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEqualityComparer}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEqualityComparer6<in T>: global::System.Collections.Generic.IEqualityComparer<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IDictionary}TKey, TValue}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTDictionary6<TKey, TValue>: global::System.Collections.Generic.IDictionary<TKey, TValue> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IObservable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTObservable6<out T>: global::System.IObservable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IObserver}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTObserver6<in T>: global::System.IObserver<T> { }
    
#endif

#if NETSTANDARD || NET || NETCOREAPP || NET45_OR_GREATER

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IReadOnlyCollection}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTReadOnlyCollection6<out T>: global::System.Collections.Generic.IReadOnlyCollection<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IReadOnlyList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTReadOnlyList6<out T>: global::System.Collections.Generic.IReadOnlyList<T> { }
    
#endif

#if NET || NETCOREAPP

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableList6<T>: global::System.Collections.Immutable.IImmutableList<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableSet}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableSet6<T>: global::System.Collections.Immutable.IImmutableSet<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableQueue}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableQueue6<T>: global::System.Collections.Immutable.IImmutableQueue<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableStack}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableStack6<T>: global::System.Collections.Immutable.IImmutableStack<T> { }
    
#endif

    /// <summary>
    /// Represents the generic type arguments marker for a reference type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal abstract class TT7 { }

    /// <summary>
    /// Represents the generic type arguments marker for a value type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal struct TTS7 { }

    /// <summary>
    /// Represents the generic type arguments marker for a enum type.
    /// </summary>
    [GenericTypeArgument]
    internal enum TTE7 { }

#if !NET35 && !NET20

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IDisposable"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTDisposable7: global::System.IDisposable { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IComparable"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparable7: global::System.IComparable { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IComparable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparable7<in T>: global::System.IComparable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IEquatable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEquatable7<T>: global::System.IEquatable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEnumerable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEnumerable7<out T>: global::System.Collections.Generic.IEnumerable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEnumerator}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEnumerator7<out T>: global::System.Collections.Generic.IEnumerator<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.ICollection}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTCollection7<T>: global::System.Collections.Generic.ICollection<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTList7<T>: global::System.Collections.Generic.IList<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.ISet}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTSet7<T>: global::System.Collections.Generic.ISet<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IComparer}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparer7<in T>: global::System.Collections.Generic.IComparer<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEqualityComparer}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEqualityComparer7<in T>: global::System.Collections.Generic.IEqualityComparer<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IDictionary}TKey, TValue}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTDictionary7<TKey, TValue>: global::System.Collections.Generic.IDictionary<TKey, TValue> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IObservable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTObservable7<out T>: global::System.IObservable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IObserver}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTObserver7<in T>: global::System.IObserver<T> { }
    
#endif

#if NETSTANDARD || NET || NETCOREAPP || NET45_OR_GREATER

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IReadOnlyCollection}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTReadOnlyCollection7<out T>: global::System.Collections.Generic.IReadOnlyCollection<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IReadOnlyList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTReadOnlyList7<out T>: global::System.Collections.Generic.IReadOnlyList<T> { }
    
#endif

#if NET || NETCOREAPP

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableList7<T>: global::System.Collections.Immutable.IImmutableList<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableSet}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableSet7<T>: global::System.Collections.Immutable.IImmutableSet<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableQueue}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableQueue7<T>: global::System.Collections.Immutable.IImmutableQueue<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableStack}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableStack7<T>: global::System.Collections.Immutable.IImmutableStack<T> { }
    
#endif

    /// <summary>
    /// Represents the generic type arguments marker for a reference type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal abstract class TT8 { }

    /// <summary>
    /// Represents the generic type arguments marker for a value type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal struct TTS8 { }

    /// <summary>
    /// Represents the generic type arguments marker for a enum type.
    /// </summary>
    [GenericTypeArgument]
    internal enum TTE8 { }

#if !NET35 && !NET20

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IDisposable"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTDisposable8: global::System.IDisposable { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IComparable"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparable8: global::System.IComparable { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IComparable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparable8<in T>: global::System.IComparable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IEquatable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEquatable8<T>: global::System.IEquatable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEnumerable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEnumerable8<out T>: global::System.Collections.Generic.IEnumerable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEnumerator}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEnumerator8<out T>: global::System.Collections.Generic.IEnumerator<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.ICollection}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTCollection8<T>: global::System.Collections.Generic.ICollection<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTList8<T>: global::System.Collections.Generic.IList<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.ISet}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTSet8<T>: global::System.Collections.Generic.ISet<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IComparer}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTComparer8<in T>: global::System.Collections.Generic.IComparer<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IEqualityComparer}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTEqualityComparer8<in T>: global::System.Collections.Generic.IEqualityComparer<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IDictionary}TKey, TValue}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTDictionary8<TKey, TValue>: global::System.Collections.Generic.IDictionary<TKey, TValue> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IObservable}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTObservable8<out T>: global::System.IObservable<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.IObserver}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTObserver8<in T>: global::System.IObserver<T> { }
    
#endif

#if NETSTANDARD || NET || NETCOREAPP || NET45_OR_GREATER

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IReadOnlyCollection}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTReadOnlyCollection8<out T>: global::System.Collections.Generic.IReadOnlyCollection<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Generic.IReadOnlyList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTReadOnlyList8<out T>: global::System.Collections.Generic.IReadOnlyList<T> { }
    
#endif

#if NET || NETCOREAPP

    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableList}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableList8<T>: global::System.Collections.Immutable.IImmutableList<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableSet}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableSet8<T>: global::System.Collections.Immutable.IImmutableSet<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableQueue}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableQueue8<T>: global::System.Collections.Immutable.IImmutableQueue<T> { }
    
    /// <summary>
    /// Represents the generic type arguments marker for <see cref="global::System.Collections.Immutable.IImmutableStack}T}"/>.
    /// </summary>
    [GenericTypeArgument]
    internal interface TTImmutableStack8<T>: global::System.Collections.Immutable.IImmutableStack<T> { }
    
#endif

    /// <summary>
    /// Represents the generic type arguments marker for a reference type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal abstract class TT9 { }

    /// <summary>
    /// Represents the generic type arguments marker for a value type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal struct TTS9 { }

    /// <summary>
    /// Represents the generic type arguments marker for a enum type.
    /// </summary>
    [GenericTypeArgument]
    internal enum TTE9 { }

    /// <summary>
    /// Represents the generic type arguments marker for a reference type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal abstract class TT10 { }

    /// <summary>
    /// Represents the generic type arguments marker for a value type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal struct TTS10 { }

    /// <summary>
    /// Represents the generic type arguments marker for a enum type.
    /// </summary>
    [GenericTypeArgument]
    internal enum TTE10 { }

    /// <summary>
    /// Represents the generic type arguments marker for a reference type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal abstract class TT11 { }

    /// <summary>
    /// Represents the generic type arguments marker for a value type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal struct TTS11 { }

    /// <summary>
    /// Represents the generic type arguments marker for a enum type.
    /// </summary>
    [GenericTypeArgument]
    internal enum TTE11 { }

    /// <summary>
    /// Represents the generic type arguments marker for a reference type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal abstract class TT12 { }

    /// <summary>
    /// Represents the generic type arguments marker for a value type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal struct TTS12 { }

    /// <summary>
    /// Represents the generic type arguments marker for a enum type.
    /// </summary>
    [GenericTypeArgument]
    internal enum TTE12 { }

    /// <summary>
    /// Represents the generic type arguments marker for a reference type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal abstract class TT13 { }

    /// <summary>
    /// Represents the generic type arguments marker for a value type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal struct TTS13 { }

    /// <summary>
    /// Represents the generic type arguments marker for a enum type.
    /// </summary>
    [GenericTypeArgument]
    internal enum TTE13 { }

    /// <summary>
    /// Represents the generic type arguments marker for a reference type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal abstract class TT14 { }

    /// <summary>
    /// Represents the generic type arguments marker for a value type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal struct TTS14 { }

    /// <summary>
    /// Represents the generic type arguments marker for a enum type.
    /// </summary>
    [GenericTypeArgument]
    internal enum TTE14 { }

    /// <summary>
    /// Represents the generic type arguments marker for a reference type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal abstract class TT15 { }

    /// <summary>
    /// Represents the generic type arguments marker for a value type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal struct TTS15 { }

    /// <summary>
    /// Represents the generic type arguments marker for a enum type.
    /// </summary>
    [GenericTypeArgument]
    internal enum TTE15 { }

    /// <summary>
    /// Represents the generic type arguments marker for a reference type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal abstract class TT16 { }

    /// <summary>
    /// Represents the generic type arguments marker for a value type.
    /// </summary>
    [GenericTypeArgument]
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    internal struct TTS16 { }

    /// <summary>
    /// Represents the generic type arguments marker for a enum type.
    /// </summary>
    [GenericTypeArgument]
    internal enum TTE16 { }

}
#pragma warning restore
#endif