// <auto-generated/>
#if !PUREDI_API_SUPPRESSION || PUREDI_API_V2
#pragma warning disable

#if !PUREDI_API_INTERFACE_SUPPRESSION
namespace Pure.DI
{
    /// <summary>
    /// Generates an interface from the attributed class.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
    [global::System.CodeDom.Compiler.GeneratedCode("Pure.DI", "")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class GenerateInterfaceAttribute : global::System.Attribute
    {
        /// <summary>
        /// Generates an interface from the attributed class.
        /// </summary>
        internal GenerateInterfaceAttribute(
            string namespaceName = default(string),
            string interfaceName = default(string),
            bool asInternal = false) { }
    }

    /// <summary>
    /// Ignores a class member when generating an interface.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method | global::System.AttributeTargets.Property | global::System.AttributeTargets.Event)]
    [global::System.CodeDom.Compiler.GeneratedCode("Pure.DI", "")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class IgnoreInterfaceAttribute : global::System.Attribute
    {
    }
}

#endif
#pragma warning restore
#endif