namespace Pure.DI.Core;

internal class CodeClassBuilder : IBuilder<ComposerInfo, ComposerInfo>
{
    private readonly IBuilder<ComposerInfo, ComposerInfo> _usingDeclarationsBuilder;
    private readonly ImmutableArray<IBuilder<ComposerInfo, ComposerInfo>> _codeBuilders;
    
    public CodeClassBuilder(
        [IoC.Tag(WellknownTag.UsingDeclarationsBuilder)] IBuilder<ComposerInfo, ComposerInfo> usingDeclarationsBuilder,
        [IoC.Tag(WellknownTag.SingletonFieldsBuilder)] IBuilder<ComposerInfo, ComposerInfo> singletonFieldsBuilder,
        [IoC.Tag(WellknownTag.ArgFieldsBuilder)] IBuilder<ComposerInfo, ComposerInfo> argFieldsBuilder,
        [IoC.Tag(WellknownTag.PrimaryConstructorBuilder)] IBuilder<ComposerInfo, ComposerInfo> primaryConstructorBuilder,
        [IoC.Tag(WellknownTag.DefaultConstructorBuilder)] IBuilder<ComposerInfo, ComposerInfo> defaultConstructorBuilder,
        [IoC.Tag(WellknownTag.ChildConstructorBuilder)] IBuilder<ComposerInfo, ComposerInfo> childConstructorBuilder,
        [IoC.Tag(WellknownTag.RootPropertiesBuilder)] IBuilder<ComposerInfo, ComposerInfo> rootPropertiesBuilder,
        [IoC.Tag(WellknownTag.DisposeMethodBuilder)] IBuilder<ComposerInfo, ComposerInfo> disposeMethodBuilder)
    {
        _usingDeclarationsBuilder = usingDeclarationsBuilder;
        _codeBuilders = ImmutableArray.Create(
            singletonFieldsBuilder,
            argFieldsBuilder,
            primaryConstructorBuilder,
            defaultConstructorBuilder,
            childConstructorBuilder,
            rootPropertiesBuilder,
            disposeMethodBuilder);
    }

    public ComposerInfo Build(ComposerInfo composer, CancellationToken cancellationToken)
    {
        var code = composer.Code;
        code.AppendLine("// <auto-generated/>");
        
        composer = _usingDeclarationsBuilder.Build(composer, cancellationToken);

        var nsIndent = Disposables.Empty;
        if (!string.IsNullOrWhiteSpace(composer.Namespace))
        {
            code.AppendLine($"namespace {composer.Namespace}");
            code.AppendLine("{");
            nsIndent = code.Indent();
        }

        code.AppendLine("[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        var implementingInterfaces = composer.Singletons.Any() ? $": {CodeConstants.DisposableTypeName}" : "";
        code.AppendLine($"partial class {composer.ClassName}{implementingInterfaces}");
        code.AppendLine("{");

        using (code.Indent())
        {
            // Generate class members
            foreach (var builder in _codeBuilders)
            {
                cancellationToken.ThrowIfCancellationRequested();
                composer = builder.Build(composer, cancellationToken);
            }
        }

        code.AppendLine("}");

        // ReSharper disable once InvertIf
        if (!string.IsNullOrWhiteSpace(composer.Namespace))
        {
            // ReSharper disable once RedundantAssignment
            nsIndent.Dispose();
            code.AppendLine("}");
        }

        return composer;
    }
}