namespace Pure.DI.Core;

static class LogMetadata
{
    private const string HelpLinkBaseUrl =
        "https://github.com/DevTeam/Pure.DI/blob/master/DIAGNOSTICS.md";

    public static string? GetHelpLink(string id) =>
        id switch
        {
            LogId.ErrorUnableToResolve => $"{HelpLinkBaseUrl}#die000",
            LogId.ErrorInvalidBinding => $"{HelpLinkBaseUrl}#die001",
            LogId.ErrorInvalidBindingDueToCompilation => $"{HelpLinkBaseUrl}#die002",
            LogId.ErrorInvalidCompositionTypeName => $"{HelpLinkBaseUrl}#die003",
            LogId.ErrorInvalidRootName => $"{HelpLinkBaseUrl}#die004",
            LogId.ErrorDuplicateRootName => $"{HelpLinkBaseUrl}#die005",
            LogId.ErrorInvalidArgumentName => $"{HelpLinkBaseUrl}#die006",
            LogId.ErrorCompositionArgGenericMarker => $"{HelpLinkBaseUrl}#die007",
            LogId.ErrorAccumulatorTypeGenericMarker => $"{HelpLinkBaseUrl}#die008",
            LogId.ErrorAccumulatorCannotAccumulateGenericMarker => $"{HelpLinkBaseUrl}#die009",
            LogId.ErrorSpecialTypeGenericMarker => $"{HelpLinkBaseUrl}#die010",
            LogId.ErrorNotImplementedContract => $"{HelpLinkBaseUrl}#die011",
            LogId.ErrorInvalidAttributeArgumentPosition => $"{HelpLinkBaseUrl}#die012",
            LogId.ErrorAttributeMemberCannotBeProcessed => $"{HelpLinkBaseUrl}#die013",
            LogId.ErrorInvalidRootType => $"{HelpLinkBaseUrl}#die014",
            LogId.ErrorInvalidRootsType => $"{HelpLinkBaseUrl}#die015",
            LogId.ErrorNoTypeForWildcard => $"{HelpLinkBaseUrl}#die016",
            LogId.ErrorInvalidBuildersType => $"{HelpLinkBaseUrl}#die017",
            LogId.ErrorInvalidBuilderType => $"{HelpLinkBaseUrl}#die018",
            LogId.ErrorTooManyTypeParameters => $"{HelpLinkBaseUrl}#die019",
            LogId.ErrorAsyncFactoryNotSupported => $"{HelpLinkBaseUrl}#die020",
            LogId.ErrorNotSupportedSyntax => $"{HelpLinkBaseUrl}#die021",
            LogId.ErrorMustBeValueOfType => $"{HelpLinkBaseUrl}#die022",
            LogId.ErrorInvalidIdentifier => $"{HelpLinkBaseUrl}#die023",
            LogId.ErrorCannotUseContextDirectly => $"{HelpLinkBaseUrl}#die024",
            LogId.ErrorInvalidNumberOfInitializers => $"{HelpLinkBaseUrl}#die025",
            LogId.ErrorLifetimeDoesNotSupportCyclicDependencies => $"{HelpLinkBaseUrl}#die026",
            LogId.ErrorTooLargeComposition => $"{HelpLinkBaseUrl}#die027",
            LogId.ErrorCannotConstructAbstractType => $"{HelpLinkBaseUrl}#die028",
            LogId.ErrorNoAccessibleConstructor => $"{HelpLinkBaseUrl}#die029",
            LogId.ErrorCannotBuildDependencyGraph => $"{HelpLinkBaseUrl}#die030",
            LogId.ErrorMaximumNumberOfIterations => $"{HelpLinkBaseUrl}#die031",
            LogId.ErrorNoAccessibleConstructorForTagOn => $"{HelpLinkBaseUrl}#die032",
            LogId.ErrorNoAccessibleMethodForTagOn => $"{HelpLinkBaseUrl}#die033",
            LogId.ErrorNoAccessibleFieldOrPropertyForTagOn => $"{HelpLinkBaseUrl}#die034",
            LogId.ErrorMustBeApiCall => $"{HelpLinkBaseUrl}#die035",
            LogId.ErrorInvalidRegularExpression => $"{HelpLinkBaseUrl}#die036",
            LogId.ErrorInvalidWildcard => $"{HelpLinkBaseUrl}#die037",
            LogId.ErrorCannotFindSetup => $"{HelpLinkBaseUrl}#die038",
            LogId.ErrorCyclicDependency => $"{HelpLinkBaseUrl}#die039",
            LogId.ErrorNotSupportedLanguageVersion => $"{HelpLinkBaseUrl}#die040",
            LogId.ErrorLifetimeDefect => $"{HelpLinkBaseUrl}#die041",
            LogId.ErrorTypeCannotBeInferred => $"{HelpLinkBaseUrl}#die042",
            LogId.ErrorUnhandled => $"{HelpLinkBaseUrl}#die043",
            LogId.ErrorSetupContextNameIsRequired => $"{HelpLinkBaseUrl}#die044",
            LogId.WarningOverriddenBinding => $"{HelpLinkBaseUrl}#diw000",
            LogId.WarningNoRoots => $"{HelpLinkBaseUrl}#diw001",
            LogId.WarningNotImplementedContract => $"{HelpLinkBaseUrl}#diw002",
            LogId.WarningBindingNotUsed => $"{HelpLinkBaseUrl}#diw003",
            LogId.WarningInjectionSiteNotUsed => $"{HelpLinkBaseUrl}#diw004",
            LogId.WarningRootArgInResolveMethod => $"{HelpLinkBaseUrl}#diw005",
            LogId.WarningTypeArgInResolveMethod => $"{HelpLinkBaseUrl}#diw006",
            LogId.WarningInstanceMemberInDependsOnSetup => $"{HelpLinkBaseUrl}#diw007",
            LogId.WarningGenerateInterfaceOnNonPublicMember => $"{HelpLinkBaseUrl}#diw008",
            LogId.WarningGenerateInterfaceOnStaticMember => $"{HelpLinkBaseUrl}#diw009",
            LogId.WarningGenerateInterfaceSelectiveEmpty => $"{HelpLinkBaseUrl}#diw010",
            LogId.InfoGenerationInterrupted => $"{HelpLinkBaseUrl}#dii000",
            LogId.InfoNotImplementedContract => $"{HelpLinkBaseUrl}#dii001",
            _ => null
        };

    public static string GetCategory(string id) =>
        id switch
        {
            LogId.ErrorInvalidBinding => "Bindings",
            LogId.ErrorInvalidBindingDueToCompilation => "Bindings",
            LogId.ErrorInvalidArgumentName => "Bindings",
            LogId.ErrorCompositionArgGenericMarker => "Bindings",
            LogId.ErrorAccumulatorTypeGenericMarker => "Bindings",
            LogId.ErrorAccumulatorCannotAccumulateGenericMarker => "Bindings",
            LogId.ErrorSpecialTypeGenericMarker => "Bindings",
            LogId.ErrorNotImplementedContract => "Bindings",
            LogId.WarningNotImplementedContract => "Bindings",
            LogId.InfoNotImplementedContract => "Bindings",
            LogId.WarningBindingNotUsed => "Bindings",
            LogId.WarningOverriddenBinding => "Bindings",

            LogId.ErrorInvalidCompositionTypeName => "Setup",
            LogId.ErrorInvalidRootName => "Setup",
            LogId.ErrorDuplicateRootName => "Setup",
            LogId.ErrorInvalidRootType => "Setup",
            LogId.ErrorInvalidRootsType => "Setup",
            LogId.ErrorNoTypeForWildcard => "Setup",
            LogId.ErrorInvalidBuildersType => "Setup",
            LogId.ErrorInvalidBuilderType => "Setup",
            LogId.ErrorCannotFindSetup => "Setup",
            LogId.WarningNoRoots => "Setup",
            LogId.WarningRootArgInResolveMethod => "Setup",
            LogId.WarningTypeArgInResolveMethod => "Setup",
            LogId.WarningInstanceMemberInDependsOnSetup => "Setup",
            LogId.ErrorSetupContextNameIsRequired => "Setup",

            LogId.ErrorAsyncFactoryNotSupported => "Factories",
            LogId.ErrorCannotUseContextDirectly => "Factories",
            LogId.ErrorInvalidNumberOfInitializers => "Factories",
            LogId.ErrorLifetimeDoesNotSupportCyclicDependencies => "Factories",

            LogId.ErrorUnableToResolve => "Validation",
            LogId.ErrorCyclicDependency => "Validation",
            LogId.ErrorTooLargeComposition => "Validation",
            LogId.ErrorCannotConstructAbstractType => "Validation",
            LogId.ErrorNoAccessibleConstructor => "Validation",
            LogId.ErrorCannotBuildDependencyGraph => "Validation",
            LogId.ErrorMaximumNumberOfIterations => "Validation",
            LogId.ErrorNoAccessibleConstructorForTagOn => "Validation",
            LogId.ErrorNoAccessibleMethodForTagOn => "Validation",
            LogId.ErrorNoAccessibleFieldOrPropertyForTagOn => "Validation",
            LogId.ErrorMustBeApiCall => "Validation",
            LogId.ErrorMustBeValueOfType => "Validation",
            LogId.ErrorInvalidIdentifier => "Validation",
            LogId.ErrorInvalidRegularExpression => "Validation",
            LogId.ErrorInvalidWildcard => "Validation",
            LogId.ErrorTooManyTypeParameters => "Validation",
            LogId.ErrorNotSupportedSyntax => "Validation",
            LogId.ErrorNotSupportedLanguageVersion => "Validation",
            LogId.ErrorLifetimeDefect => "Validation",
            LogId.ErrorTypeCannotBeInferred => "Validation",
            LogId.ErrorInvalidAttributeArgumentPosition => "Validation",
            LogId.ErrorAttributeMemberCannotBeProcessed => "Validation",
            LogId.WarningInjectionSiteNotUsed => "Validation",
            LogId.WarningGenerateInterfaceOnNonPublicMember => "Validation",
            LogId.WarningGenerateInterfaceOnStaticMember => "Validation",
            LogId.WarningGenerateInterfaceSelectiveEmpty => "Validation",

            // ReSharper disable once RedundantSwitchExpressionArms
            LogId.InfoGenerationInterrupted => "General",
            // ReSharper disable once RedundantSwitchExpressionArms
            LogId.ErrorUnhandled => "General",
            _ => "General"
        };

    public static string? GetDescription(string id) =>
        id switch
        {
            LogId.ErrorUnableToResolve => Strings.Description_ErrorUnableToResolve,
            LogId.ErrorInvalidBinding => Strings.Description_ErrorInvalidBinding,
            LogId.ErrorInvalidBindingDueToCompilation => Strings.Description_ErrorInvalidBindingDueToCompilation,
            LogId.ErrorInvalidCompositionTypeName => Strings.Description_ErrorInvalidCompositionTypeName,
            LogId.ErrorInvalidRootName => Strings.Description_ErrorInvalidRootName,
            LogId.ErrorDuplicateRootName => Strings.Description_ErrorDuplicateRootName,
            LogId.ErrorInvalidArgumentName => Strings.Description_ErrorInvalidArgumentName,
            LogId.ErrorCompositionArgGenericMarker => Strings.Description_ErrorCompositionArgGenericMarker,
            LogId.ErrorAccumulatorTypeGenericMarker => Strings.Description_ErrorAccumulatorTypeGenericMarker,
            LogId.ErrorAccumulatorCannotAccumulateGenericMarker => Strings.Description_ErrorAccumulatorCannotAccumulateGenericMarker,
            LogId.ErrorSpecialTypeGenericMarker => Strings.Description_ErrorSpecialTypeGenericMarker,
            LogId.ErrorNotImplementedContract => Strings.Description_ErrorNotImplementedContract,
            LogId.ErrorInvalidAttributeArgumentPosition => Strings.Description_ErrorInvalidAttributeArgumentPosition,
            LogId.ErrorAttributeMemberCannotBeProcessed => Strings.Description_ErrorAttributeMemberCannotBeProcessed,
            LogId.ErrorInvalidRootType => Strings.Description_ErrorInvalidRootType,
            LogId.ErrorInvalidRootsType => Strings.Description_ErrorInvalidRootsType,
            LogId.ErrorNoTypeForWildcard => Strings.Description_ErrorNoTypeForWildcard,
            LogId.ErrorInvalidBuildersType => Strings.Description_ErrorInvalidBuildersType,
            LogId.ErrorInvalidBuilderType => Strings.Description_ErrorInvalidBuilderType,
            LogId.ErrorTooManyTypeParameters => Strings.Description_ErrorTooManyTypeParameters,
            LogId.ErrorAsyncFactoryNotSupported => Strings.Description_ErrorAsyncFactoryNotSupported,
            LogId.ErrorNotSupportedSyntax => Strings.Description_ErrorNotSupportedSyntax,
            LogId.ErrorMustBeValueOfType => Strings.Description_ErrorMustBeValueOfType,
            LogId.ErrorInvalidIdentifier => Strings.Description_ErrorInvalidIdentifier,
            LogId.ErrorCannotUseContextDirectly => Strings.Description_ErrorCannotUseContextDirectly,
            LogId.ErrorInvalidNumberOfInitializers => Strings.Description_ErrorInvalidNumberOfInitializers,
            LogId.ErrorLifetimeDoesNotSupportCyclicDependencies => Strings.Description_ErrorLifetimeDoesNotSupportCyclicDependencies,
            LogId.ErrorTooLargeComposition => Strings.Description_ErrorTooLargeComposition,
            LogId.ErrorCannotConstructAbstractType => Strings.Description_ErrorCannotConstructAbstractType,
            LogId.ErrorNoAccessibleConstructor => Strings.Description_ErrorNoAccessibleConstructor,
            LogId.ErrorCannotBuildDependencyGraph => Strings.Description_ErrorCannotBuildDependencyGraph,
            LogId.ErrorMaximumNumberOfIterations => Strings.Description_ErrorMaximumNumberOfIterations,
            LogId.ErrorNoAccessibleConstructorForTagOn => Strings.Description_ErrorNoAccessibleConstructorForTagOn,
            LogId.ErrorNoAccessibleMethodForTagOn => Strings.Description_ErrorNoAccessibleMethodForTagOn,
            LogId.ErrorNoAccessibleFieldOrPropertyForTagOn => Strings.Description_ErrorNoAccessibleFieldOrPropertyForTagOn,
            LogId.ErrorMustBeApiCall => Strings.Description_ErrorMustBeApiCall,
            LogId.ErrorInvalidRegularExpression => Strings.Description_ErrorInvalidRegularExpression,
            LogId.ErrorInvalidWildcard => Strings.Description_ErrorInvalidWildcard,
            LogId.ErrorCannotFindSetup => Strings.Description_ErrorCannotFindSetup,
            LogId.ErrorCyclicDependency => Strings.Description_ErrorCyclicDependency,
            LogId.ErrorNotSupportedLanguageVersion => Strings.Description_ErrorNotSupportedLanguageVersion,
            LogId.ErrorLifetimeDefect => Strings.Description_ErrorLifetimeDefect,
            LogId.ErrorTypeCannotBeInferred => Strings.Description_ErrorTypeCannotBeInferred,
            LogId.ErrorSetupContextNameIsRequired => Strings.Description_ErrorSetupContextNameIsRequired,
            LogId.WarningOverriddenBinding => Strings.Description_WarningOverriddenBinding,
            LogId.WarningNoRoots => Strings.Description_WarningNoRoots,
            LogId.WarningNotImplementedContract => Strings.Description_WarningNotImplementedContract,
            LogId.WarningBindingNotUsed => Strings.Description_WarningBindingNotUsed,
            LogId.WarningInjectionSiteNotUsed => Strings.Description_WarningInjectionSiteNotUsed,
            LogId.WarningRootArgInResolveMethod => Strings.Description_WarningRootArgInResolveMethod,
            LogId.WarningTypeArgInResolveMethod => Strings.Description_WarningTypeArgInResolveMethod,
            LogId.WarningInstanceMemberInDependsOnSetup => Strings.Description_WarningInstanceMemberInDependsOnSetup,
            LogId.WarningGenerateInterfaceOnNonPublicMember => Strings.Description_WarningGenerateInterfaceOnNonPublicMember,
            LogId.WarningGenerateInterfaceOnStaticMember => Strings.Description_WarningGenerateInterfaceOnStaticMember,
            LogId.WarningGenerateInterfaceSelectiveEmpty => Strings.Description_WarningGenerateInterfaceSelectiveEmpty,
            LogId.InfoGenerationInterrupted => Strings.Description_InfoGenerationInterrupted,
            LogId.InfoNotImplementedContract => Strings.Description_InfoNotImplementedContract,
            LogId.ErrorUnhandled => Strings.Description_ErrorUnhandled,
            _ => null
        };
}
