// <auto-generated/>
#pragma warning disable CS8669
namespace Pure.DI.MS
{
    using System;
    using System.Linq.Expressions;
    using System.Reflection;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.DependencyInjection.Extensions;

    /// <summary>
    /// Base class for a Pure.DI composition that integrates with Microsoft dependency injection.
    /// </summary>
    /// <remarks>
    /// Inherit a generated composition from this type to expose Pure.DI roots through
    /// <see cref="IServiceProviderFactory{TContainerBuilder}"/> and to resolve external
    /// Microsoft dependency injection services from the generated composition. Composition roots
    /// are registered in the supplied <see cref="IServiceCollection"/> by <see cref="CreateBuilder"/>.
    /// Untagged unresolved dependencies are resolved from the Microsoft <see cref="IServiceProvider"/>;
    /// tagged unresolved dependencies require a provider that implements keyed services.
    /// </remarks>
    /// <example>
    /// <code>
    /// partial class Composition: ServiceProviderFactory&lt;Composition&gt;
    /// {
    ///     void Setup() =&gt; DI.Setup()
    ///         .Bind().As(Singleton).To&lt;WeatherForecastService&gt;()
    ///         // Registers controllers as roots
    ///         .Roots&lt;ControllerBase&gt;();
    /// }
    /// </code>
    /// </example> 
    /// <typeparam name="TComposition">The Pure.DI composition type.</typeparam>
#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1
    [global::System.CodeDom.Compiler.GeneratedCode("Pure.DI", "")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    public class ServiceProviderFactory<TComposition>: IServiceProviderFactory<IServiceCollection>
        where TComposition: ServiceProviderFactory<TComposition>
    {
        private static readonly Type KeyedServiceProviderType = Type.GetType("Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider, Microsoft.Extensions.DependencyInjection.Abstractions, Culture=neutral, PublicKeyToken=adb9793829ddae60", false);
        private static readonly MethodInfo GetKeyedServiceMethod = KeyedServiceProviderType?.GetMethod("GetKeyedService");
        private static readonly ParameterExpression TypeParameter = Expression.Parameter(typeof(Type));
        private static readonly ParameterExpression TagParameter = Expression.Parameter(typeof(object));
    
        /// <summary>
        /// Exports generated Pure.DI roots as Microsoft dependency injection service descriptors.
        /// </summary>
        private static readonly ServiceCollectionFactory<TComposition> ServiceCollectionFactory = new global::Pure.DI.MS.ServiceCollectionFactory<TComposition>();

        /// <summary>
        /// Synchronizes access to the external service provider.
        /// </summary>
        private readonly global::System.Object _lock = new global::System.Object();
    
        /// <summary>
        /// Delegate used to resolve external dependencies from the Microsoft dependency injection provider.
        /// </summary>
        private Func<Type, object, object?>? _instanceResolver;

        /// <summary>
        /// The Microsoft dependency injection provider used for unresolved external dependencies.
        /// </summary>
        private IServiceProvider _serviceProvider;

        /// <summary>
        /// Gets or sets the Microsoft dependency injection provider used for unresolved external dependencies.
        /// </summary>
        /// <remarks>
        /// The provider can be assigned only once. If it supports keyed services, tagged unresolved
        /// dependencies are resolved by key; otherwise only untagged unresolved dependencies are resolved.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Thrown when assigning <see langword="null"/>.</exception>
        /// <exception cref="InvalidOperationException">
        /// Thrown when the provider is requested before it is set, or when it is assigned more than once.
        /// </exception>
        public IServiceProvider ServiceProvider
        {
            get
            {
                lock (_lock)
                {
                    return _serviceProvider ?? throw new InvalidOperationException("The service provider has not yet been defined.");
                }
            }
            set
            {
                if (value == null) throw new ArgumentNullException(nameof(value));
                lock (_lock)
                {
                    if (_instanceResolver is not null)
                    {
                        throw new InvalidOperationException("The service provider has already been defined.");
                    }

                    _serviceProvider = value;
                    _instanceResolver = CreateInstanceResolver(value);
                }
            }
        }

        private static Func<Type, object, object> CreateInstanceResolver(IServiceProvider serviceProvider)
        {
            if (KeyedServiceProviderType != null
                && GetKeyedServiceMethod != null
                && KeyedServiceProviderType.IsAssignableFrom(serviceProvider.GetType()))
            {
                return Expression.Lambda<Func<Type, object, object>>(
                    Expression.Call(Expression.Constant(serviceProvider), GetKeyedServiceMethod, TypeParameter, TagParameter),
                    TypeParameter,
                    TagParameter).Compile();
            }

            return (type, tag) => tag == null ? serviceProvider.GetService(type) : null;
        }

        /// <summary>
        /// DI setup hints.
        /// </summary>
        [global::System.Diagnostics.Conditional("A2768DE22DE3E430C9653990D516CC9B")]
        private static void HintsSetup()
        {
            global::Pure.DI.DI.Setup(kind: global::Pure.DI.CompositionKind.Internal)
                .Hint(global::Pure.DI.Hint.OnCannotResolve, "On")
                .Hint(global::Pure.DI.Hint.OnCannotResolvePartial, "Off")
                .Hint(global::Pure.DI.Hint.OnNewRoot, "On")
                .Hint(global::Pure.DI.Hint.OnNewRootPartial, "Off")
                // Specifies not to attempt to resolve types whose fully qualified name
                // begins with Microsoft.Extensions, Microsoft.AspNetCore, Microsoft.Maui
                // since ServiceProvider will be used to retrieve them.
                .Hint(global::Pure.DI.Hint.OnCannotResolveContractTypeNameWildcard, "Microsoft.Extensions.*")
                .Hint(global::Pure.DI.Hint.OnCannotResolveContractTypeNameWildcard, "Microsoft.AspNetCore.*")
                .Hint(global::Pure.DI.Hint.OnCannotResolveContractTypeNameWildcard, "Microsoft.Maui.*")
                .Hint(global::Pure.DI.Hint.OnCannotResolveContractTypeNameWildcard, "Microsoft.EntityFrameworkCore.*");
        }

        /// <summary>
        /// Creates an <see cref="IServiceCollection"/> containing descriptors for generated Pure.DI roots.
        /// </summary>
        /// <param name="composition">The Pure.DI composition instance.</param>
        /// <returns>An <see cref="IServiceCollection"/> with descriptors for the generated roots.</returns>
        /// <exception cref="ArgumentNullException">Thrown when <paramref name="composition"/> is <see langword="null"/>.</exception>
#if NETSTANDARD2_0_OR_GREATER || NETCOREAPP || NET40_OR_GREATER || NET
        [global::System.Diagnostics.Contracts.Pure]
#endif
        protected static IServiceCollection CreateServiceCollection(TComposition composition)
        {
            if (composition == null) throw new ArgumentNullException(nameof(composition));
            return ServiceCollectionFactory.CreateServiceCollection(composition);
        }

        /// <inheritdoc />
        /// <remarks>
        /// Adds generated Pure.DI roots to the provided service collection and returns the same collection.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Thrown when <paramref name="services"/> is <see langword="null"/>.</exception>
        public IServiceCollection CreateBuilder(IServiceCollection services)
        {
            if (services == null) throw new ArgumentNullException(nameof(services));
            // Registers composition roots as services in the service collection.
            return services.Add(CreateServiceCollection((TComposition)this));
        }

        /// <inheritdoc />
        /// <exception cref="ArgumentNullException">Thrown when <paramref name="services"/> is <see langword="null"/>.</exception>
        /// <exception cref="InvalidOperationException">Thrown when the service provider has already been set.</exception>
        public IServiceProvider CreateServiceProvider(IServiceCollection services)
        {
            if (services == null) throw new ArgumentNullException(nameof(services));
            return ServiceProvider = services.BuildServiceProvider();
        }

        /// <summary>
        /// Resolves an unresolved dependency from the Microsoft dependency injection provider.
        /// </summary>
        /// <param name="tag">The dependency resolution tag, or <see langword="null"/> for the default service.</param>
        /// <param name="lifetime">The requested dependency lifetime.</param>
        /// <typeparam name="T">The dependency type.</typeparam>
        /// <returns>The resolved dependency instance.</returns>
        /// <exception cref="InvalidOperationException">Thrown when the service provider has not been set.</exception>
        /// <exception cref="CannotResolveException">
        /// Thrown when the dependency cannot be resolved, including tagged requests against providers without keyed service support.
        /// </exception>
        internal T OnCannotResolve<T>(object? tag, Lifetime lifetime)
        {
            Func<Type, object, object?>? serviceProvider;
            lock (_lock)
            {
                serviceProvider = _instanceResolver ?? throw new InvalidOperationException("Services have not yet been defined.");
            }

            return (T)(serviceProvider(typeof(T), tag)
                   ?? throw new CannotResolveException($"No composition root is registered for the type {typeof(T)}{(tag == null ? "" : $"({tag})")}.", typeof(T), tag));
        }

        /// <summary>
        /// Registers a generated Pure.DI root for export to Microsoft dependency injection.
        /// </summary>
        /// <param name="resolver">The generated root resolver.</param>
        /// <param name="name">The generated composition root name.</param>
        /// <param name="tag">The composition root tag, or <see langword="null"/> for the default root.</param>
        /// <param name="lifetime">The lifetime of the composition root.</param>
        /// <typeparam name="TContract">The contract type of the composition root.</typeparam>
        /// <typeparam name="T">The implementation type of the composition root.</typeparam>
        /// <exception cref="ArgumentNullException">Thrown when <paramref name="resolver"/> is <see langword="null"/>.</exception>
        internal static void OnNewRoot<TContract, T>(
            IResolver<TComposition, TContract> resolver,
            string name, object tag, Lifetime lifetime)
        {
            if (resolver == null) throw new ArgumentNullException(nameof(resolver));
            ServiceCollectionFactory.AddResolver(resolver, tag, lifetime);
        }
    }
#pragma warning restore
}
