namespace Pure.DI.InterfaceGeneration;

sealed class InterfaceAttributeSources : IInterfaceAttributeSources
{
    internal InterfaceAttributeSources()
    {
        GenerateInterfaceAttributeSource = $$"""
            // <auto-generated />
            using System;

            namespace Pure.DI
            {
                /// <summary>
                /// Generates an interface from the attributed class.
                /// </summary>
                [AttributeUsage(AttributeTargets.Class)]
                [global::System.CodeDom.Compiler.GeneratedCode("{{Core.Names.GeneratorName}}", "")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                internal sealed class {{Names.GenerateInterfaceAttributeName}}Attribute : Attribute
                {
                    /// <summary>
                    /// Generates an interface from the attributed class.
                    /// </summary>
                    internal {{Names.GenerateInterfaceAttributeName}}Attribute(
                        string {{Names.NamespaceParameterName}} = default(string),
                        string {{Names.InterfaceParameterName}} = default(string),
                        bool {{Names.AsInternalParameterName}} = false) { }
                }
            }
            """;

        IgnoreInterfaceAttributeSource = $$"""
            // <auto-generated />
            using System;

            namespace Pure.DI
            {
                /// <summary>
                /// Ignores a class member when generating an interface.
                /// </summary>
                [AttributeUsage(AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Event)]
                [global::System.CodeDom.Compiler.GeneratedCode("{{Core.Names.GeneratorName}}", "")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                internal sealed class {{Names.IgnoreInterfaceAttributeName}}Attribute : Attribute
                {
                    internal {{Names.IgnoreInterfaceAttributeName}}Attribute() { }
                }
            }
            """;
    }

    public string GenerateInterfaceAttributeSource { get; }

    public string IgnoreInterfaceAttributeSource { get; }
}
