namespace Pure.DI.InterfaceGeneration;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Pure.DI.Core;

sealed class InterfaceCodeBuilder(string namespaceName, string interfaceName, string accessLevel)
{
    private const string Autogenerated = """
                                         //--------------------------------------------------------------------------------------------------
                                         // <auto-generated>
                                         //     This code was generated by a tool.
                                         //
                                         //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
                                         // </auto-generated>
                                         //--------------------------------------------------------------------------------------------------


                                         """;

    private readonly List<PropertyInfo> _propertyInfos = [];
    private readonly List<MethodInfo> _methodInfos = [];
    private readonly List<EventInfo> _events = [];
    private string _classDocumentation = string.Empty;
    private string _genericType = string.Empty;

    public bool HasNullable { get; set; }

    public void AddPropertyToInterface(string name, string type, bool hasGet, PropertySetKind hasSet, bool isRef, string documentation) =>
        _propertyInfos.Add(new PropertyInfo(name, type, hasGet, hasSet, isRef, documentation));

    public void AddGeneric(string v) => _genericType = v;

    public void AddClassDocumentation(string documentation) => _classDocumentation = documentation;

    public void AddMethodToInterface(string name, string returnType, string documentation, HashSet<string> parameters, List<(string Arg, string WhereConstraint)> genericArgs) =>
        _methodInfos.Add(new MethodInfo(name, returnType, documentation, parameters.ToImmutableArray(), genericArgs.ToImmutableArray()));

    public void AddEventToInterface(string name, string type, string documentation) =>
        _events.Add(new EventInfo(name, type, documentation));

    public string Build()
    {
        var lines = new Lines();
        AppendRaw(lines, Autogenerated);

        if (HasNullable)
        {
            lines.AppendLine("#nullable enable");
        }

        lines.AppendLine("using System;");
        lines.AppendLine();

        if (!string.IsNullOrWhiteSpace(namespaceName))
        {
            lines.AppendLine($"namespace {namespaceName}");
            lines.AppendLine("{");
            lines.IncIndent();
        }

        AppendAndNormalizeMultipleLines(lines, _classDocumentation);
        lines.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"{Core.Names.GeneratorName}\", \"\")]");
        lines.AppendLine($"{accessLevel} partial interface {interfaceName}{_genericType}");
        lines.AppendLine("{");
        lines.IncIndent();

        foreach (var prop in _propertyInfos)
        {
            AppendAndNormalizeMultipleLines(lines, prop.Documentation);
            var @ref = prop.IsRef ? "ref " : string.Empty;
            var get = prop.HasGet ? "get; " : string.Empty;
            var set = GetSet(prop.SetKind);
            lines.AppendLine($"{@ref}{prop.Type} {prop.Name} {{ {get}{set}}}");
            lines.AppendLine();
        }

        foreach (var method in _methodInfos)
        {
            BuildMethod(lines, method);
        }

        foreach (var evt in _events)
        {
            AppendAndNormalizeMultipleLines(lines, evt.Documentation);
            lines.AppendLine($"event {evt.Type} {evt.Name};");
            lines.AppendLine();
        }

        lines.DecIndent();
        lines.AppendLine("}");

        if (!string.IsNullOrWhiteSpace(namespaceName))
        {
            lines.DecIndent();
            lines.AppendLine("}");
        }

        if (HasNullable)
        {
            lines.AppendLine("#nullable restore");
        }

        return lines.ToString();
    }

    private static string GetSet(PropertySetKind propSetKind) =>
        propSetKind switch
        {
            PropertySetKind.NoSet => string.Empty,
            PropertySetKind.Always => "set; ",
            PropertySetKind.Init => "init; ",
            _ => throw new ArgumentOutOfRangeException(nameof(propSetKind), propSetKind, null)
        };

    private static void BuildMethod(Lines lines, MethodInfo method)
    {
        AppendAndNormalizeMultipleLines(lines, method.Documentation);
        var sb = new StringBuilder($"{method.ReturnType} {method.Name}");

        if (method.GenericArgs.Length > 0)
        {
            sb.Append($"<{string.Join(", ", method.GenericArgs.Select(a => a.Arg))}>");
        }

        sb.Append($"({string.Join(", ", method.Parameters)})");

        if (method.GenericArgs.Length > 0)
        {
            var constraints = method.GenericArgs
                .Where(a => !string.IsNullOrWhiteSpace(a.WhereConstraint))
                .Select(a => a.WhereConstraint);
            sb.Append($" {string.Join(" ", constraints)}");
        }

        sb.Append(';');
        lines.AppendLine(sb.ToString());
        lines.AppendLine();
    }

    private static void AppendAndNormalizeMultipleLines(Lines lines, string doc)
    {
        if (string.IsNullOrWhiteSpace(doc))
        {
            return;
        }

        foreach (var line in doc.Split([Environment.NewLine], StringSplitOptions.None))
        {
            lines.AppendLine(line.TrimStart());
        }
    }

    private static void AppendRaw(Lines lines, string raw)
    {
        foreach (var line in raw.Split([Environment.NewLine], StringSplitOptions.None))
        {
            lines.AppendLine(line);
        }
    }
}
