// ReSharper disable ClassNeverInstantiated.Global

namespace Pure.DI.Core.Code;

using Parts;
using static LinesExtensions;
using static Tag;

sealed class CompositionClassBuilder(
    [Tag(UsingDeclarations)] IBuilder<CompositionCode, CompositionCode> usingDeclarations,
    IEnumerable<IClassPartBuilder> classPartBuilders,
    [Tag(typeof(ClassCommenter))] ICommenter<Unit> classCommenter,
    IInformation information,
    CancellationToken cancellationToken)
    : IBuilder<CompositionCode, CompositionCode>
{
    private readonly List<IClassPartBuilder> _classPartBuilders = classPartBuilders.OrderBy(i => i.Part).ToList();

    public CompositionCode Build(CompositionCode composition)
    {
        var code = composition.Code;
        code.AppendLine("// <auto-generated/>");
        code.AppendLine($"// by {information.Description}");
        if (composition.Compilation.Options.NullableContextOptions != NullableContextOptions.Disable)
        {
            code.AppendLine("#nullable enable annotations");
        }

        code.AppendLine();
        composition = usingDeclarations.Build(composition);

        var nsIndent = Disposables.Empty;
        var name = composition.Source.Source.Name;
        if (!string.IsNullOrWhiteSpace(name.Namespace))
        {
            code.AppendLine($"namespace {name.Namespace}");
            code.AppendLine(BlockStart);
            nsIndent = code.Indent();
        }

        classCommenter.AddComments(composition, Unit.Shared);
        code.AppendLine(new Line(int.MinValue, "#if !NET20 && !NET35 && !NETSTANDARD1_0 && !NETSTANDARD1_1 && !NETSTANDARD1_2 && !NETSTANDARD1_3 && !NETSTANDARD1_4 && !NETSTANDARD1_5 && !NETSTANDARD1_6 && !NETCOREAPP1_0 && !NETCOREAPP1_1 // Code coverage"));
        code.AppendLine($"[{Names.SystemNamespace}Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        code.AppendLine(new Line(int.MinValue, "#endif // Code coverage"));
        var implementingInterfaces = new List<string>();
        if (composition.TotalDisposablesCount > 0)
        {
            implementingInterfaces.Add(Names.IDisposableTypeName);
        }

        if (composition.AsyncDisposableCount > 0)
        {
            implementingInterfaces.Add(Names.IAsyncDisposableTypeName);
        }

        code.AppendLine($"partial class {name.ClassName}{(implementingInterfaces.Count > 0 ? ": " + string.Join(", ", implementingInterfaces) : "")}");
        using (code.CreateBlock())
        {
            var prevCount = composition.MembersCount;
            // Generate class members
            foreach (var builder in _classPartBuilders)
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (prevCount != composition.MembersCount)
                {
                    code.AppendLine();
                    prevCount = composition.MembersCount;
                }

                composition = builder.Build(composition);
            }
        }

        // ReSharper disable once InvertIf
        if (!string.IsNullOrWhiteSpace(name.Namespace))
        {
            // ReSharper disable once RedundantAssignment
            nsIndent.Dispose();
            code.AppendLine(BlockFinish);
        }

        return composition;
    }
}