// ReSharper disable ClassNeverInstantiated.Global
namespace Pure.DI.Core.Code;

internal class SetupClassAttributeBuilder(IInformation information) : IBuilder<MdSetup, SetupClassAttribute>
{
    public SetupClassAttribute Build(MdSetup setup)
    {
        var setupInvocationExpression = setup.Source.AncestorsAndSelf().OfType<InvocationExpressionSyntax>().FirstOrDefault();
        var lastInvocationExpression = setupInvocationExpression?.AncestorsAndSelf().OfType<InvocationExpressionSyntax>().LastOrDefault();
        var setupCode = lastInvocationExpression?.ToFullString();
        if (string.IsNullOrWhiteSpace(setupCode))
        {
            throw new CompileErrorException($"Unable to process \"{setup.Name.FullName}\" setup.", setup.Source.GetLocation(), LogId.ErrorInvalidMetadata);
        }

        var usingDirectives = string.Join(";", setup.UsingDirectives.Select(i => i.UsingDirectives).SelectMany(i => i).Distinct().OrderBy(i => i));
        var staticUsingDirectives = string.Join(";", setup.UsingDirectives.Select(i => i.StaticUsingDirectives).SelectMany(i => i).Distinct().OrderBy(i => i));
        
        var code = new LinesBuilder();
        code.AppendLine("// <auto-generated/>");
        code.AppendLine($"// by {information.Description}");
        code.AppendLine("#nullable enable");
        code.AppendLine("#pragma warning disable");
        code.AppendLine();
        code.AppendLine($"[assembly:global::Pure.DI.SetupAttribute({Escape(setupCode)}, \"{usingDirectives}\", \"{staticUsingDirectives}\")]");
        code.AppendLine();
        code.AppendLine("#pragma warning restore");
        return new SetupClassAttribute(setup, code);
    }

    private static string Escape(string? text)
    {
        if (text is null)
        {
            return "\"\"";
        }

        text = text.Trim();
        var sb = new StringBuilder(text.Length << 1);
        sb.Append("\"");
        var hasNewLine = false;
        foreach (var ch in text)
        {
            if (ch == '"')
            {
                sb.Append('\\');
                sb.Append('"');
                hasNewLine = false;
                continue;
            }
            
            if (ch == '\\')
            {
                sb.Append('\\');
                sb.Append('\\');
                hasNewLine = false;
                continue;
            }

            if (SyntaxFacts.IsNewLine(ch))
            {
                if (!hasNewLine)
                {
                    sb.Append('\\');
                    sb.Append('n');
                    hasNewLine = true;
                }

                continue;
            }

            sb.Append(ch);
            hasNewLine = false;
        }
        
        sb.Append("\"");
        return sb.ToString();
    }
}