// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable UnusedVariable
namespace Pure.DI.Core.Code;

using static LinesExtensions;

sealed class TagClassBuilder(
    IInformation information,
    ISmartTags smartTags,
    IFormatter formatter,
    IComments comments,
    ITypes types,
    CancellationToken cancellationToken)
    : IBuilder<TagContext, IEnumerable<TagCode>>
{
    private static readonly Dictionary<SmartTagKind, SmartTagInfo> Info = new()
    {
        {
            SmartTagKind.Tag,
            new SmartTagInfo(
                nameof(Tag),
                [
                    "Shared",
                    nameof(Tag.Unique),
                    nameof(Tag.Type),
                    nameof(Tag.Any),
                    nameof(Tag.On),
                    nameof(Tag.OnConstructorArg),
                    nameof(Tag.OnMember)
                ])
        },
        { SmartTagKind.Name, new SmartTagInfo(nameof(Name), []) }
    };

    public IEnumerable<TagCode> Build(TagContext tagContext)
    {
        var tagTags = smartTags.Get(SmartTagKind.Tag);
        var nameTags = smartTags.Get(SmartTagKind.Name);

        if (tagTags.Count == 0 && nameTags.Count == 0)
        {
            yield break;
        }

        if (tagTags.Count > 0)
        {
            var tagToDependenciesMap = new Dictionary<string, Dictionary<CompositionCode, HashSet<string>>>(StringComparer.Ordinal);
            foreach (var composition in tagContext.Compositions)
            {
                foreach (var dependency in composition.Source.Graph.Edges)
                {
                    if (dependency.Injection.Tag is not string tag)
                    {
                        continue;
                    }

                    if (!tagToDependenciesMap.TryGetValue(tag, out var byComposition))
                    {
                        byComposition = new Dictionary<CompositionCode, HashSet<string>>();
                        tagToDependenciesMap.Add(tag, byComposition);
                    }

                    if (!byComposition.TryGetValue(composition, out var dependencies))
                    {
                        dependencies = new HashSet<string>(StringComparer.Ordinal);
                        byComposition.Add(composition, dependencies);
                    }

                    var tagText = comments.Escape(dependency.Injection.Tag is not MdTagOnSites ? $"({dependency.Injection.Tag})" : "");
                    var target = formatter.FormatRef(dependency.Target.Type);
                    var injectin = types.TypeEquals(dependency.Injection.Type, dependency.Source.Type)
                        ? ""
                        : formatter.FormatRef(dependency.Injection.Type);
                    var source = formatter.FormatRef(dependency.Source.Type);
                    var sourceLifetime = formatter.FormatRef(dependency.Source.Lifetime);
                    dependencies.Add($"/// <item>{target} &lt;-- {injectin}{tagText} -- {source} as {sourceLifetime}</item>");
                }
            }

            var tagToDependencies = tagToDependenciesMap.ToDictionary(
                i => i.Key,
                i => i.Value.Select(j => (j.Key, dependencies: j.Value.OrderBy(k => k))));

            if (TryBuildTagCode(SmartTagKind.Tag, tagTags, tagToDependencies, AddTagComments, out var tagCode))
            {
                yield return (TagCode)tagCode;
            }
        }

        if (TryBuildTagCode(SmartTagKind.Name, nameTags, Unit.Shared, DoesNotAddComments, out var nameCode))
        {
            yield return (TagCode)nameCode;
        }
    }

    private bool TryBuildTagCode<TContext>(
        SmartTagKind kind,
        IReadOnlyCollection<SmartTag> tags,
        TContext context,
        Commenter<TContext> commenter,
        [NotNullWhen(true)] out TagCode? tagCode)
    {
        if (!Info.TryGetValue(kind, out var info))
        {
            tagCode = null;
            return false;
        }

        cancellationToken.ThrowIfCancellationRequested();

        var filteredTags = tags.Where(i => !info.Exclusions.Contains(i.Name)).ToList();
        if (filteredTags.Count == 0)
        {
            tagCode = null;
            return false;
        }

        var code = new Lines();
        code.AppendLine("// <auto-generated/>");
        code.AppendLine($"// by {information.Description}");
        code.AppendLine($"namespace {Names.GeneratorName}");
        using (code.CreateBlock())
        {
            code.AppendLine($"internal partial class {info.ClassName}");
            using (code.CreateBlock())
            {
                var isFirst = true;
                foreach (var tag in filteredTags)
                {
                    if (isFirst)
                    {
                        isFirst = false;
                    }
                    else
                    {
                        code.AppendLine();
                    }

                    commenter(tag, code, context);
                    code.AppendLine($"public const string {tag.Name} = {tag.Name.ValueToString()};");
                }
            }
        }

        tagCode = new TagCode(info.ClassName, code);
        return true;
    }

    private delegate void Commenter<in TContext>(SmartTag tag, Lines code, TContext context);

    private void AddTagComments(
        SmartTag tag,
        Lines code,
        Dictionary<string, IEnumerable<(CompositionCode composition, IOrderedEnumerable<string> dependencies)>> tagToDependencies)
    {
        code.AppendLine("/// <summary>");
        code.AppendLine($"/// Atomically generated smart tag with value {comments.Escape(tag.Name.ValueToString())}.");
        if (tagToDependencies.TryGetValue(tag.Name, out var dependenciesByComposition))
        {
            code.AppendLine("/// It's used for:");
            code.AppendLine("/// <br/>");
            foreach (var (composition, dependencies) in dependenciesByComposition)
            {
                code.AppendLine("/// <br/>");
                code.AppendLine($"/// class {formatter.FormatRef(composition.Source.Source.Name.FullName)}");
                code.AppendLine("/// <list type=\"number\">");
                foreach (var dependency in dependencies)
                {
                    code.AppendLine(dependency);
                }

                code.AppendLine("/// </list>");
            }
        }

        code.AppendLine("/// </summary>");
    }

    private static void DoesNotAddComments(SmartTag tag, Lines code, Unit context)
    {
    }

    private readonly record struct SmartTagInfo(string ClassName, HashSet<string> Exclusions);
}
