//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pure.DI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pure.DI.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The accumulator cannot accumulate instances based on a generic type marker..
        /// </summary>
        internal static string Error_AccumulatorCannotAccumulateGenericTypeMarker {
            get {
                return ResourceManager.GetString("Error_AccumulatorCannotAccumulateGenericTypeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The accumulator type cannot be based on a generic type marker..
        /// </summary>
        internal static string Error_AccumulatorTypeCannotBeGenericTypeMarker {
            get {
                return ResourceManager.GetString("Error_AccumulatorTypeCannotBeGenericTypeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asynchronous factory with the &apos;async&apos; keyword is not supported..
        /// </summary>
        internal static string Error_AsynchronousFactoryWithAsyncNotSupported {
            get {
                return ResourceManager.GetString("Error_AsynchronousFactoryWithAsyncNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot build the dependency graph..
        /// </summary>
        internal static string Error_CannotBuildDependencyGraph {
            get {
                return ResourceManager.GetString("Error_CannotBuildDependencyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The composition argument type cannot be based on a generic type marker..
        /// </summary>
        internal static string Error_CompositionArgumentTypeCannotBeGenericTypeMarker {
            get {
                return ResourceManager.GetString("Error_CompositionArgumentTypeCannotBeGenericTypeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot build the dependency graph..
        /// </summary>
        internal static string Error_DependencyGraphConstractionFailure {
            get {
                return ResourceManager.GetString("Error_DependencyGraphConstractionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binding is incorrectly defined..
        /// </summary>
        internal static string Error_InvalidBinding {
            get {
                return ResourceManager.GetString("Error_InvalidBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid binding due to a compilation error..
        /// </summary>
        internal static string Error_InvalidBindingDueToCompilationError {
            get {
                return ResourceManager.GetString("Error_InvalidBindingDueToCompilationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid builders type..
        /// </summary>
        internal static string Error_InvalidBuildersType {
            get {
                return ResourceManager.GetString("Error_InvalidBuildersType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid builder type..
        /// </summary>
        internal static string Error_InvalidBuilderType {
            get {
                return ResourceManager.GetString("Error_InvalidBuilderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of initializers..
        /// </summary>
        internal static string Error_InvalidNumberOfInitializers {
            get {
                return ResourceManager.GetString("Error_InvalidNumberOfInitializers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid roots type..
        /// </summary>
        internal static string Error_InvalidRootsRype {
            get {
                return ResourceManager.GetString("Error_InvalidRootsRype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid root type..
        /// </summary>
        internal static string Error_InvalidRootType {
            get {
                return ResourceManager.GetString("Error_InvalidRootType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The special type cannot be based on a generic type marker..
        /// </summary>
        internal static string Error_SpecialTypeCannotBeGenericTypeMarker {
            get {
                return ResourceManager.GetString("Error_SpecialTypeCannotBeGenericTypeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of type {1} cannot be processed because it is marked with multiple mutually exclusive attributes..
        /// </summary>
        internal static string Error_Template_AttributeMemberCannotBeProcessed {
            get {
                return ResourceManager.GetString("Error_Template_AttributeMemberCannotBeProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot construct an instance of {0} because no accessible constructor is available..
        /// </summary>
        internal static string Error_Template_CannotBeInstantiatedNoAccessibleConstructor {
            get {
                return ResourceManager.GetString("Error_Template_CannotBeInstantiatedNoAccessibleConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot construct an instance of {0} because it is an abstract type..
        /// </summary>
        internal static string Error_Template_CannotConstructAbstractType {
            get {
                return ResourceManager.GetString("Error_Template_CannotConstructAbstractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find setup &quot;{0}&quot;..
        /// </summary>
        internal static string Error_Template_CannotFindSetup {
            get {
                return ResourceManager.GetString("Error_Template_CannotFindSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use &quot;{0}&quot; directly. Only its methods or properties are accessible..
        /// </summary>
        internal static string Error_Template_CannotUseContextDirectly {
            get {
                return ResourceManager.GetString("Error_Template_CannotUseContextDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup context name must be specified for DependsOn..
        /// </summary>
        internal static string Error_SetupContextNameIsRequired {
            get {
                return ResourceManager.GetString("Error_SetupContextNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic dependency found: {0}..
        /// </summary>
        internal static string Error_Template_CyclicDependency {
            get {
                return ResourceManager.GetString("Error_Template_CyclicDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument name &quot;{0}&quot;..
        /// </summary>
        internal static string Error_Template_InvalidArgumentName {
            get {
                return ResourceManager.GetString("Error_Template_InvalidArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The position of argument {0} of attribute {1} is out of range [0..{2}]..
        /// </summary>
        internal static string Error_Template_InvalidAttributeArgumentPosition {
            get {
                return ResourceManager.GetString("Error_Template_InvalidAttributeArgumentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid composition type name &quot;{0}&quot;..
        /// </summary>
        internal static string Error_Template_InvalidCompositionTypeName {
            get {
                return ResourceManager.GetString("Error_Template_InvalidCompositionTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid identifier &quot;{0}&quot;..
        /// </summary>
        internal static string Error_Template_InvalidIdentifier {
            get {
                return ResourceManager.GetString("Error_Template_InvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression {0}: &quot;{1}&quot;..
        /// </summary>
        internal static string Error_Template_InvalidRegularExpression {
            get {
                return ResourceManager.GetString("Error_Template_InvalidRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid root name &quot;{0}&quot;..
        /// </summary>
        internal static string Error_Template_InvalidRootName {
            get {
                return ResourceManager.GetString("Error_Template_InvalidRootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid wildcard {0}: &quot;{1}&quot;..
        /// </summary>
        internal static string Error_Template_InvalidWildcard {
            get {
                return ResourceManager.GetString("Error_Template_InvalidWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} lifetime does not support cyclic dependencies..
        /// </summary>
        internal static string Error_Template_LifetimeDoesNotSupportCyclicDependencies {
            get {
                return ResourceManager.GetString("Error_Template_LifetimeDoesNotSupportCyclicDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of iterations {0} was exceeded while building the optimal dependency graph. Refine the dependency graph..
        /// </summary>
        internal static string Error_Template_MaximumNumberOfIterations {
            get {
                return ResourceManager.GetString("Error_Template_MaximumNumberOfIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a constant value of type {1} or a special API call..
        /// </summary>
        internal static string Error_Template_MustBeApiCall {
            get {
                return ResourceManager.GetString("Error_Template_MustBeApiCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a non-null value of type {1}..
        /// </summary>
        internal static string Error_Template_MustBeValueOfType {
            get {
                return ResourceManager.GetString("Error_Template_MustBeValueOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No accessible non-static constructor of type {0} found with an argument matching &quot;{1}&quot;..
        /// </summary>
        internal static string Error_Template_NoAccessibleConstructor {
            get {
                return ResourceManager.GetString("Error_Template_NoAccessibleConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No accessible non-static field or property of type {1} matching &quot;{0}&quot; was found..
        /// </summary>
        internal static string Error_Template_NoAccessibleFieldOrProperty {
            get {
                return ResourceManager.GetString("Error_Template_NoAccessibleFieldOrProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No accessible non-static method of type {0} found with name &quot;{1}&quot; and an argument matching &quot;{2}&quot;..
        /// </summary>
        internal static string Error_Template_NoAccessibleMethod {
            get {
                return ResourceManager.GetString("Error_Template_NoAccessibleMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not implement {1}..
        /// </summary>
        internal static string Error_Template_NotImplement {
            get {
                return ResourceManager.GetString("Error_Template_NotImplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not supported..
        /// </summary>
        internal static string Error_Template_NotSupported {
            get {
                return ResourceManager.GetString("Error_Template_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No type inheriting from {0} was found that matches the &quot;{1}&quot; filter..
        /// </summary>
        internal static string Error_Template_NoTypeForWildcard {
            get {
                return ResourceManager.GetString("Error_Template_NoTypeForWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The composition root &quot;{0}&quot; duplicates the previously declared root &quot;{1}&quot;..
        /// </summary>
        internal static string Error_Template_RootDuplicate {
            get {
                return ResourceManager.GetString("Error_Template_RootDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static root {0} of type {1} cannot use lifetime {2} directly or through a dependency..
        /// </summary>
        internal static string Error_Template_StaticRootCannotUseLifetime {
            get {
                return ResourceManager.GetString("Error_Template_StaticRootCannotUseLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The composition is too large. Stopped at dependency #{0}..
        /// </summary>
        internal static string Error_Template_TooLargeComposition {
            get {
                return ResourceManager.GetString("Error_Template_TooLargeComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} with lifetime {1} requires direct or transitive injection of type {2} with lifetime {3}, which may lead to data leakage or unexpected behavior..
        /// </summary>
        internal static string Error_Template_TypeWithLifetimeRequiresDirectOrTransitiveInjection {
            get {
                return ResourceManager.GetString("Error_Template_TypeWithLifetimeRequiresDirectOrTransitiveInjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve &quot;{0}&quot; in {1}..
        /// </summary>
        internal static string Error_Template_UnableToResolve {
            get {
                return ResourceManager.GetString("Error_Template_UnableToResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not support C# {1}. Use language version {2} or newer..
        /// </summary>
        internal static string Error_Template_UnsupportLanguage {
            get {
                return ResourceManager.GetString("Error_Template_UnsupportLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many type parameters..
        /// </summary>
        internal static string Error_TooManyTypeParameters {
            get {
                return ResourceManager.GetString("Error_TooManyTypeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine the type. Try specifying it explicitly..
        /// </summary>
        internal static string Error_TypeCannotBeInferred {
            get {
                return ResourceManager.GetString("Error_TypeCannotBeInferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error occurred..
        /// </summary>
        internal static string Error_UnhandledError {
            get {
                return ResourceManager.GetString("Error_UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code generation was aborted..
        /// </summary>
        internal static string Info_CodeGenerationAborted {
            get {
                return ResourceManager.GetString("Info_CodeGenerationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binding is not used..
        /// </summary>
        internal static string Warning_BindingIsNotUsed {
            get {
                return ResourceManager.GetString("Warning_BindingIsNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No composition roots are declared. Add at least one root..
        /// </summary>
        internal static string Warning_NoRoots {
            get {
                return ResourceManager.GetString("Warning_NoRoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binding uses instance member "{0}" from setup "{1}" that is applied via DependsOn or CompositionKind.Internal/Global. This member will not exist in the dependent composition. Use Arg/RootArg or a separate context object..
        /// </summary>
        internal static string Warning_Template_InstanceMemberInDependsOnSetup {
            get {
                return ResourceManager.GetString("Warning_Template_InstanceMemberInDependsOnSetup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The [GenerateInterface] attribute on element &quot;{0}&quot; is ignored for interface &quot;{1}&quot; because the element is not public..
        /// </summary>
        internal static string Warning_Template_GenerateInterfaceOnNonPublicMember {
            get {
                return ResourceManager.GetString("Warning_Template_GenerateInterfaceOnNonPublicMember", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The [GenerateInterface] attribute on element &quot;{0}&quot; is ignored for interface &quot;{1}&quot; because the element is static..
        /// </summary>
        internal static string Warning_Template_GenerateInterfaceOnStaticMember {
            get {
                return ResourceManager.GetString("Warning_Template_GenerateInterfaceOnStaticMember", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selective interface generation for &quot;{0}&quot; produced an empty interface because no eligible elements remained..
        /// </summary>
        internal static string Warning_Template_GenerateInterfaceSelectiveEmpty {
            get {
                return ResourceManager.GetString("Warning_Template_GenerateInterfaceSelectiveEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binding for {0} has been overridden..
        /// </summary>
        internal static string Warning_Template_BindingHasBeenOverridden {
            get {
                return ResourceManager.GetString("Warning_Template_BindingHasBeenOverridden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag &quot;{0}&quot; at the injection site is not used..
        /// </summary>
        internal static string Warning_Template_InjectionSiteIsNotUsed {
            get {
                return ResourceManager.GetString("Warning_Template_InjectionSiteIsNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root {0} cannot be resolved by Resolve methods due to arguments {1}, so an exception will be thrown when attempting to do so..
        /// </summary>
        internal static string Warning_Template_RootCannotBeResolvedByResolveMethods {
            get {
                return ResourceManager.GetString("Warning_Template_RootCannotBeResolvedByResolveMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve a dependency in the object graph..
        /// </summary>
        internal static string Description_ErrorUnableToResolve {
            get {
                return ResourceManager.GetString("Description_ErrorUnableToResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding cannot be built due to missing binding metadata..
        /// </summary>
        internal static string Description_ErrorInvalidBinding {
            get {
                return ResourceManager.GetString("Description_ErrorInvalidBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding is invalid because the compiler reported errors..
        /// </summary>
        internal static string Description_ErrorInvalidBindingDueToCompilation {
            get {
                return ResourceManager.GetString("Description_ErrorInvalidBindingDueToCompilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition type name is invalid..
        /// </summary>
        internal static string Description_ErrorInvalidCompositionTypeName {
            get {
                return ResourceManager.GetString("Description_ErrorInvalidCompositionTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root name is invalid..
        /// </summary>
        internal static string Description_ErrorInvalidRootName {
            get {
                return ResourceManager.GetString("Description_ErrorInvalidRootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate root names detected..
        /// </summary>
        internal static string Description_ErrorDuplicateRootName {
            get {
                return ResourceManager.GetString("Description_ErrorDuplicateRootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument name is invalid..
        /// </summary>
        internal static string Description_ErrorInvalidArgumentName {
            get {
                return ResourceManager.GetString("Description_ErrorInvalidArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition argument type is based on a generic marker..
        /// </summary>
        internal static string Description_ErrorCompositionArgGenericMarker {
            get {
                return ResourceManager.GetString("Description_ErrorCompositionArgGenericMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulator type is based on a generic marker..
        /// </summary>
        internal static string Description_ErrorAccumulatorTypeGenericMarker {
            get {
                return ResourceManager.GetString("Description_ErrorAccumulatorTypeGenericMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulator cannot accumulate a generic marker..
        /// </summary>
        internal static string Description_ErrorAccumulatorCannotAccumulateGenericMarker {
            get {
                return ResourceManager.GetString("Description_ErrorAccumulatorCannotAccumulateGenericMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special type cannot be a generic marker..
        /// </summary>
        internal static string Description_ErrorSpecialTypeGenericMarker {
            get {
                return ResourceManager.GetString("Description_ErrorSpecialTypeGenericMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation does not implement the contract..
        /// </summary>
        internal static string Description_ErrorNotImplementedContract {
            get {
                return ResourceManager.GetString("Description_ErrorNotImplementedContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute argument position is invalid..
        /// </summary>
        internal static string Description_ErrorInvalidAttributeArgumentPosition {
            get {
                return ResourceManager.GetString("Description_ErrorInvalidAttributeArgumentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute member cannot be processed..
        /// </summary>
        internal static string Description_ErrorAttributeMemberCannotBeProcessed {
            get {
                return ResourceManager.GetString("Description_ErrorAttributeMemberCannotBeProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root type is invalid..
        /// </summary>
        internal static string Description_ErrorInvalidRootType {
            get {
                return ResourceManager.GetString("Description_ErrorInvalidRootType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roots type is invalid..
        /// </summary>
        internal static string Description_ErrorInvalidRootsType {
            get {
                return ResourceManager.GetString("Description_ErrorInvalidRootsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No type matched the wildcard filter..
        /// </summary>
        internal static string Description_ErrorNoTypeForWildcard {
            get {
                return ResourceManager.GetString("Description_ErrorNoTypeForWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builders type is invalid..
        /// </summary>
        internal static string Description_ErrorInvalidBuildersType {
            get {
                return ResourceManager.GetString("Description_ErrorInvalidBuildersType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builder type is invalid..
        /// </summary>
        internal static string Description_ErrorInvalidBuilderType {
            get {
                return ResourceManager.GetString("Description_ErrorInvalidBuilderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many type parameters provided..
        /// </summary>
        internal static string Description_ErrorTooManyTypeParameters {
            get {
                return ResourceManager.GetString("Description_ErrorTooManyTypeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async factories are not supported..
        /// </summary>
        internal static string Description_ErrorAsyncFactoryNotSupported {
            get {
                return ResourceManager.GetString("Description_ErrorAsyncFactoryNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported syntax in DI API..
        /// </summary>
        internal static string Description_ErrorNotSupportedSyntax {
            get {
                return ResourceManager.GetString("Description_ErrorNotSupportedSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be of a specific type..
        /// </summary>
        internal static string Description_ErrorMustBeValueOfType {
            get {
                return ResourceManager.GetString("Description_ErrorMustBeValueOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier is invalid..
        /// </summary>
        internal static string Description_ErrorInvalidIdentifier {
            get {
                return ResourceManager.GetString("Description_ErrorInvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context is used directly where it is not allowed..
        /// </summary>
        internal static string Description_ErrorCannotUseContextDirectly {
            get {
                return ResourceManager.GetString("Description_ErrorCannotUseContextDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DependsOn requires a setup context name when using a setup context kind..
        /// </summary>
        internal static string Description_ErrorSetupContextNameIsRequired {
            get {
                return ResourceManager.GetString("Description_ErrorSetupContextNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializers count does not match..
        /// </summary>
        internal static string Description_ErrorInvalidNumberOfInitializers {
            get {
                return ResourceManager.GetString("Description_ErrorInvalidNumberOfInitializers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifetime does not support cyclic dependencies..
        /// </summary>
        internal static string Description_ErrorLifetimeDoesNotSupportCyclicDependencies {
            get {
                return ResourceManager.GetString("Description_ErrorLifetimeDoesNotSupportCyclicDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition is too large to build..
        /// </summary>
        internal static string Description_ErrorTooLargeComposition {
            get {
                return ResourceManager.GetString("Description_ErrorTooLargeComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot construct an abstract type..
        /// </summary>
        internal static string Description_ErrorCannotConstructAbstractType {
            get {
                return ResourceManager.GetString("Description_ErrorCannotConstructAbstractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No accessible constructor found..
        /// </summary>
        internal static string Description_ErrorNoAccessibleConstructor {
            get {
                return ResourceManager.GetString("Description_ErrorNoAccessibleConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency graph cannot be built..
        /// </summary>
        internal static string Description_ErrorCannotBuildDependencyGraph {
            get {
                return ResourceManager.GetString("Description_ErrorCannotBuildDependencyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of iterations reached..
        /// </summary>
        internal static string Description_ErrorMaximumNumberOfIterations {
            get {
                return ResourceManager.GetString("Description_ErrorMaximumNumberOfIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No accessible constructor found for Tag.On..
        /// </summary>
        internal static string Description_ErrorNoAccessibleConstructorForTagOn {
            get {
                return ResourceManager.GetString("Description_ErrorNoAccessibleConstructorForTagOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No accessible method found for Tag.On..
        /// </summary>
        internal static string Description_ErrorNoAccessibleMethodForTagOn {
            get {
                return ResourceManager.GetString("Description_ErrorNoAccessibleMethodForTagOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No accessible field or property found for Tag.On..
        /// </summary>
        internal static string Description_ErrorNoAccessibleFieldOrPropertyForTagOn {
            get {
                return ResourceManager.GetString("Description_ErrorNoAccessibleFieldOrPropertyForTagOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression must be a valid API call..
        /// </summary>
        internal static string Description_ErrorMustBeApiCall {
            get {
                return ResourceManager.GetString("Description_ErrorMustBeApiCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression is invalid..
        /// </summary>
        internal static string Description_ErrorInvalidRegularExpression {
            get {
                return ResourceManager.GetString("Description_ErrorInvalidRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildcard is invalid..
        /// </summary>
        internal static string Description_ErrorInvalidWildcard {
            get {
                return ResourceManager.GetString("Description_ErrorInvalidWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DI setup could not be found..
        /// </summary>
        internal static string Description_ErrorCannotFindSetup {
            get {
                return ResourceManager.GetString("Description_ErrorCannotFindSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic dependency detected..
        /// </summary>
        internal static string Description_ErrorCyclicDependency {
            get {
                return ResourceManager.GetString("Description_ErrorCyclicDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language version is not supported..
        /// </summary>
        internal static string Description_ErrorNotSupportedLanguageVersion {
            get {
                return ResourceManager.GetString("Description_ErrorNotSupportedLanguageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifetime validation error..
        /// </summary>
        internal static string Description_ErrorLifetimeDefect {
            get {
                return ResourceManager.GetString("Description_ErrorLifetimeDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type cannot be inferred..
        /// </summary>
        internal static string Description_ErrorTypeCannotBeInferred {
            get {
                return ResourceManager.GetString("Description_ErrorTypeCannotBeInferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding has been overridden..
        /// </summary>
        internal static string Description_WarningOverriddenBinding {
            get {
                return ResourceManager.GetString("Description_WarningOverriddenBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No composition roots defined..
        /// </summary>
        internal static string Description_WarningNoRoots {
            get {
                return ResourceManager.GetString("Description_WarningNoRoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation does not implement the contract..
        /// </summary>
        internal static string Description_WarningNotImplementedContract {
            get {
                return ResourceManager.GetString("Description_WarningNotImplementedContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding is not used..
        /// </summary>
        internal static string Description_WarningBindingNotUsed {
            get {
                return ResourceManager.GetString("Description_WarningBindingNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.On injection site is not used..
        /// </summary>
        internal static string Description_WarningInjectionSiteNotUsed {
            get {
                return ResourceManager.GetString("Description_WarningInjectionSiteNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve methods are incompatible with root arguments..
        /// </summary>
        internal static string Description_WarningRootArgInResolveMethod {
            get {
                return ResourceManager.GetString("Description_WarningRootArgInResolveMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve methods are incompatible with type arguments..
        /// </summary>
        internal static string Description_WarningTypeArgInResolveMethod {
            get {
                return ResourceManager.GetString("Description_WarningTypeArgInResolveMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DependsOn uses an instance member..
        /// </summary>
        internal static string Description_WarningInstanceMemberInDependsOnSetup {
            get {
                return ResourceManager.GetString("Description_WarningInstanceMemberInDependsOnSetup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GenerateInterface is applied to a non-public element..
        /// </summary>
        internal static string Description_WarningGenerateInterfaceOnNonPublicMember {
            get {
                return ResourceManager.GetString("Description_WarningGenerateInterfaceOnNonPublicMember", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GenerateInterface is applied to a static element..
        /// </summary>
        internal static string Description_WarningGenerateInterfaceOnStaticMember {
            get {
                return ResourceManager.GetString("Description_WarningGenerateInterfaceOnStaticMember", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selective interface generation produced an empty interface..
        /// </summary>
        internal static string Description_WarningGenerateInterfaceSelectiveEmpty {
            get {
                return ResourceManager.GetString("Description_WarningGenerateInterfaceSelectiveEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation was interrupted..
        /// </summary>
        internal static string Description_InfoGenerationInterrupted {
            get {
                return ResourceManager.GetString("Description_InfoGenerationInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation does not implement the contract..
        /// </summary>
        internal static string Description_InfoNotImplementedContract {
            get {
                return ResourceManager.GetString("Description_InfoNotImplementedContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled generator error..
        /// </summary>
        internal static string Description_ErrorUnhandled {
            get {
                return ResourceManager.GetString("Description_ErrorUnhandled", resourceCulture);
            }
        }
    }
}
