//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pure.DI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pure.DI.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The accumulator cannot accumulate instances based on a generic type marker..
        /// </summary>
        internal static string Error_AccumulatorCannotAccumulateGenericTypeMarker {
            get {
                return ResourceManager.GetString("Error_AccumulatorCannotAccumulateGenericTypeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The accumulator type cannot be based on a generic type marker..
        /// </summary>
        internal static string Error_AccumulatorTypeCannotBeGenericTypeMarker {
            get {
                return ResourceManager.GetString("Error_AccumulatorTypeCannotBeGenericTypeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asynchronous factory with the async keyword is not supported..
        /// </summary>
        internal static string Error_AsynchronousFactoryWithAsyncNotSupported {
            get {
                return ResourceManager.GetString("Error_AsynchronousFactoryWithAsyncNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot build a dependency graph..
        /// </summary>
        internal static string Error_CannotBuildDependencyGraph {
            get {
                return ResourceManager.GetString("Error_CannotBuildDependencyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The composition argument type cannot be based on a generic type marker..
        /// </summary>
        internal static string Error_CompositionArgumentTypeCannotBeGenericTypeMarker {
            get {
                return ResourceManager.GetString("Error_CompositionArgumentTypeCannotBeGenericTypeMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to construct a dependency graph..
        /// </summary>
        internal static string Error_DependencyGraphConstractionFailure {
            get {
                return ResourceManager.GetString("Error_DependencyGraphConstractionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binding is defined incorrectly..
        /// </summary>
        internal static string Error_InvalidBinding {
            get {
                return ResourceManager.GetString("Error_InvalidBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid binding due to compilation error..
        /// </summary>
        internal static string Error_InvalidBindingDueToCompilationError {
            get {
                return ResourceManager.GetString("Error_InvalidBindingDueToCompilationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid builders type..
        /// </summary>
        internal static string Error_InvalidBuildersType {
            get {
                return ResourceManager.GetString("Error_InvalidBuildersType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid builder type..
        /// </summary>
        internal static string Error_InvalidBuilderType {
            get {
                return ResourceManager.GetString("Error_InvalidBuilderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of initializers..
        /// </summary>
        internal static string Error_InvalidNumberOfInitializers {
            get {
                return ResourceManager.GetString("Error_InvalidNumberOfInitializers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid roots type..
        /// </summary>
        internal static string Error_InvalidRootsRype {
            get {
                return ResourceManager.GetString("Error_InvalidRootsRype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid root type..
        /// </summary>
        internal static string Error_InvalidRootType {
            get {
                return ResourceManager.GetString("Error_InvalidRootType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of the type {1} cannot be processed because it is marked with multiple mutually exclusive attributes..
        /// </summary>
        internal static string Error_Template_AttributeMemberCannotBeProcessed {
            get {
                return ResourceManager.GetString("Error_Template_AttributeMemberCannotBeProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of {0} cannot be instantiated due to no accessible constructor available..
        /// </summary>
        internal static string Error_Template_CannotBeInstantiatedNoAccessibleConstructor {
            get {
                return ResourceManager.GetString("Error_Template_CannotBeInstantiatedNoAccessibleConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of {0} cannot be constructed because it is an abstract type..
        /// </summary>
        internal static string Error_Template_CannotConstructAbstractType {
            get {
                return ResourceManager.GetString("Error_Template_CannotConstructAbstractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find setup &quot;{0}&quot;..
        /// </summary>
        internal static string Error_Template_CannotFindSetup {
            get {
                return ResourceManager.GetString("Error_Template_CannotFindSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to use &quot;{0}&quot; directly. Only its methods or properties can be used..
        /// </summary>
        internal static string Error_Template_CannotUseContextDirectly {
            get {
                return ResourceManager.GetString("Error_Template_CannotUseContextDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic dependency has been found: {0}..
        /// </summary>
        internal static string Error_Template_CyclicDependency {
            get {
                return ResourceManager.GetString("Error_Template_CyclicDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument name &quot;{0}&quot;..
        /// </summary>
        internal static string Error_Template_InvalidArgumentName {
            get {
                return ResourceManager.GetString("Error_Template_InvalidArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument position {0} of attribute {1} is out of range [0..{2}]..
        /// </summary>
        internal static string Error_Template_InvalidAttributeArgumentPosition {
            get {
                return ResourceManager.GetString("Error_Template_InvalidAttributeArgumentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid composition type name &quot;{0}&quot;..
        /// </summary>
        internal static string Error_Template_InvalidCompositionTypeName {
            get {
                return ResourceManager.GetString("Error_Template_InvalidCompositionTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid identifier &quot;{0}&quot;..
        /// </summary>
        internal static string Error_Template_InvalidIdentifier {
            get {
                return ResourceManager.GetString("Error_Template_InvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression {0}: &quot;{1}&quot;..
        /// </summary>
        internal static string Error_Template_InvalidRegularExpression {
            get {
                return ResourceManager.GetString("Error_Template_InvalidRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid root name &quot;{0}&quot;..
        /// </summary>
        internal static string Error_Template_InvalidRootName {
            get {
                return ResourceManager.GetString("Error_Template_InvalidRootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid wildcard {0}: &quot;{1}&quot;..
        /// </summary>
        internal static string Error_Template_InvalidWildcard {
            get {
                return ResourceManager.GetString("Error_Template_InvalidWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lifetime does not support cyclic dependencies..
        /// </summary>
        internal static string Error_Template_LifetimeDoesNotSupportCyclicDependencies {
            get {
                return ResourceManager.GetString("Error_Template_LifetimeDoesNotSupportCyclicDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of iterations {0} was exceeded  was exceeded when building the optimal dependency graph. Try to specify the dependency graph more accurately..
        /// </summary>
        internal static string Error_Template_MaximumNumberOfIterations {
            get {
                return ResourceManager.GetString("Error_Template_MaximumNumberOfIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a constant value of type {1} or a special API call..
        /// </summary>
        internal static string Error_Template_MustBeApiCall {
            get {
                return ResourceManager.GetString("Error_Template_MustBeApiCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a non-null value of type {1}..
        /// </summary>
        internal static string Error_Template_MustBeValueOfType {
            get {
                return ResourceManager.GetString("Error_Template_MustBeValueOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no accessible non-static constructor of type {0} with an argument matching &quot;{1}&quot;..
        /// </summary>
        internal static string Error_Template_NoAccessibleConstructor {
            get {
                return ResourceManager.GetString("Error_Template_NoAccessibleConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no accessible non-static writable field or property matched with &quot;{0}&quot; of {1}..
        /// </summary>
        internal static string Error_Template_NoAccessibleFieldOrProperty {
            get {
                return ResourceManager.GetString("Error_Template_NoAccessibleFieldOrProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no accessible non-static method of type {0} with a name matching &quot;{1}&quot; an argument matching &quot;{2}&quot;..
        /// </summary>
        internal static string Error_Template_NoAccessibleMethod {
            get {
                return ResourceManager.GetString("Error_Template_NoAccessibleMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not implement {1}..
        /// </summary>
        internal static string Error_Template_NotImplement {
            get {
                return ResourceManager.GetString("Error_Template_NotImplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not supported..
        /// </summary>
        internal static string Error_Template_NotSupported {
            get {
                return ResourceManager.GetString("Error_Template_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no type found that inherits from {0} whose name matches the &quot;{1}&quot; filter..
        /// </summary>
        internal static string Error_Template_NoTypeForWildcard {
            get {
                return ResourceManager.GetString("Error_Template_NoTypeForWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The composition root &quot;{0}&quot; duplicates the previously declared root &quot;{1}&quot;..
        /// </summary>
        internal static string Error_Template_RootDuplicate {
            get {
                return ResourceManager.GetString("Error_Template_RootDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static root {0} of type {1} cannot use lifetime {2} directly or through a dependency..
        /// </summary>
        internal static string Error_Template_StaicRootCannotUseLifetime {
            get {
                return ResourceManager.GetString("Error_Template_StaicRootCannotUseLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The composition is too large. Stopped on the #{0} dependency..
        /// </summary>
        internal static string Error_Template_TooLargeComposition {
            get {
                return ResourceManager.GetString("Error_Template_TooLargeComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} with lifetime {1} requires direct or transitive dependency injection of type {2} with lifetime {3}, which can lead to data leakage and unexpected behavior..
        /// </summary>
        internal static string Error_Template_TypeWithLifetimeRequiresDirectOrTransitiveInjection {
            get {
                return ResourceManager.GetString("Error_Template_TypeWithLifetimeRequiresDirectOrTransitiveInjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve &quot;{0}&quot; in {1}..
        /// </summary>
        internal static string Error_Template_UnableToResolve {
            get {
                return ResourceManager.GetString("Error_Template_UnableToResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not support C# {1}. Please use language version {2} or greater..
        /// </summary>
        internal static string Error_Template_UnsupportLanguage {
            get {
                return ResourceManager.GetString("Error_Template_UnsupportLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many type parameters..
        /// </summary>
        internal static string Error_TooManyTypeParameters {
            get {
                return ResourceManager.GetString("Error_TooManyTypeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine type. Try specifying it explicitly..
        /// </summary>
        internal static string Error_TypeCannotBeInferred {
            get {
                return ResourceManager.GetString("Error_TypeCannotBeInferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error has occurred..
        /// </summary>
        internal static string Error_UnhandledError {
            get {
                return ResourceManager.GetString("Error_UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code generation aborted..
        /// </summary>
        internal static string Info_CodeGenerationAborted {
            get {
                return ResourceManager.GetString("Info_CodeGenerationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding is not used..
        /// </summary>
        internal static string Warning_BindingIsNotUsed {
            get {
                return ResourceManager.GetString("Warning_BindingIsNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the composition roots are declared. Add at least one root..
        /// </summary>
        internal static string Warning_NoRoots {
            get {
                return ResourceManager.GetString("Warning_NoRoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binding for {0} has been overridden..
        /// </summary>
        internal static string Warning_Template_BindingHasBeenOverridden {
            get {
                return ResourceManager.GetString("Warning_Template_BindingHasBeenOverridden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; of the tag on the injection site is not used..
        /// </summary>
        internal static string Warning_Template_InjectionSiteIsNotUsed {
            get {
                return ResourceManager.GetString("Warning_Template_InjectionSiteIsNotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root {0} cannot be resolved using Resolve methods due it has arguments {1}, so an exception will be thrown when trying to do it..
        /// </summary>
        internal static string Warning_Template_RootCannotBeResolvedByResolveMethods {
            get {
                return ResourceManager.GetString("Warning_Template_RootCannotBeResolvedByResolveMethods", resourceCulture);
            }
        }
    }
}
