namespace Pure.DI;

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

internal static class RegisterAttributesExtensions
{
    public static string GenerateInterfaceAttributeSource { get; } =
        $$"""
        // <auto-generated />
        using System;

        namespace Pure.DI
        {
            /// <summary>
            /// Generates an interface from the attributed class.
            /// </summary>
            [AttributeUsage(AttributeTargets.Class)]
            [global::System.CodeDom.Compiler.GeneratedCode("Pure.DI", "")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            internal sealed class {{InterfaceGenerator.GenerateInterfaceAttributeName}}Attribute : Attribute
            {
                /// <summary>
                /// Generates an interface from the attributed class.
                /// </summary>
                internal {{InterfaceGenerator.GenerateInterfaceAttributeName}}Attribute(
                    string {{InterfaceGenerator.NamespaceParameterName}} = default(string),
                    string {{InterfaceGenerator.InterfaceParameterName}} = default(string),
                    bool {{InterfaceGenerator.AsInternalParameterName}} = false) { }
            }
        }
        """;

    public static string IgnoreInterfaceAttributeSource { get; } =
        $$$"""
        // <auto-generated />
        using System;

        namespace Pure.DI
        {
            /// <summary>
            /// Ignores a class member when generating an interface.
            /// </summary>
            [AttributeUsage(AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Event)]
            [global::System.CodeDom.Compiler.GeneratedCode("Pure.DI", "")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            internal sealed class {{{InterfaceGenerator.IgnoreInterfaceAttributeName}}}Attribute : Attribute
            {
                internal {{{InterfaceGenerator.IgnoreInterfaceAttributeName}}}Attribute() { }
            }
        }
        """;
}
